// <auto-generated>
//     This file was generated by uniffi-bindgen-cs v0.11.0+v0.31.0
//     See https://github.com/NordSecurity/uniffi-bindgen-cs for more information.
// </auto-generated>

#nullable enable




using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.IO;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Threading;
using System.Threading.Tasks;
namespace uniffi.livekit_token_source
{



// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

[StructLayout(LayoutKind.Sequential)]
internal struct RustBuffer {
    public ulong capacity;
    public ulong len;
    public IntPtr data;

    public static RustBuffer Alloc(int size) {
        return _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            var buffer = _UniFFILib.ffi_livekit_token_source_rustbuffer_alloc(Convert.ToUInt64(size), ref status);
            if (buffer.data == IntPtr.Zero) {
                throw new AllocationException($"RustBuffer.Alloc() returned null data pointer (size={size})");
            }
            return buffer;
        });
    }

    public static void Free(RustBuffer buffer) {
        _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            _UniFFILib.ffi_livekit_token_source_rustbuffer_free(buffer, ref status);
        });
    }

    public static BigEndianStream MemoryStream(IntPtr data, long length)
    {
        unsafe
        {
            return new BigEndianStream(new UnmanagedMemoryStream((byte*)data.ToPointer(), length));
        }
    }

    public BigEndianStream AsStream()
    {
        unsafe
        {
            return new BigEndianStream(
                new UnmanagedMemoryStream((byte*)data.ToPointer(), Convert.ToInt64(len))
            );
        }
    }

    public BigEndianStream AsWriteableStream()
    {
        unsafe
        {
            return new BigEndianStream(
                new UnmanagedMemoryStream(
                    (byte*)data.ToPointer(),
                    Convert.ToInt64(capacity),
                    Convert.ToInt64(capacity),
                    FileAccess.Write
                )
            );
        }
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to managed memory, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

[StructLayout(LayoutKind.Sequential)]
internal struct ForeignBytes {
    public int length;
    public IntPtr data;
}


// The FfiConverter interface handles converter types to and from the FFI
//
// All implementing objects should be public to support external types.  When a
// type is external we need to import it's FfiConverter.
internal abstract class FfiConverter<CsType, FfiType> {
    // Convert an FFI type to a C# type
    public abstract CsType Lift(FfiType value);

    // Convert C# type to an FFI type
    public abstract FfiType Lower(CsType value);

    // Read a C# type from a `ByteBuffer`
    public abstract CsType Read(BigEndianStream stream);

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    public abstract int AllocationSize(CsType value);

    // Write a C# type to a `ByteBuffer`
    public abstract void Write(CsType value, BigEndianStream stream);

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    public RustBuffer LowerIntoRustBuffer(CsType value) {
        var rbuf = RustBuffer.Alloc(AllocationSize(value));
        try {
            var stream = rbuf.AsWriteableStream();
            Write(value, stream);
            rbuf.len = Convert.ToUInt64(stream.Position);
            return rbuf;
        } catch {
            RustBuffer.Free(rbuf);
            throw;
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    protected CsType LiftFromRustBuffer(RustBuffer rbuf) {
        var stream = rbuf.AsStream();
        try {
           var item = Read(stream);
           if (stream.HasRemaining()) {
               throw new InternalException("junk remaining in buffer after lifting, something is very wrong!!");
           }
           return item;
        } finally {
            RustBuffer.Free(rbuf);
        }
    }
}

// FfiConverter that uses `RustBuffer` as the FfiType
internal abstract class FfiConverterRustBuffer<CsType>: FfiConverter<CsType, RustBuffer> {
    public override CsType Lift(RustBuffer value) {
        return LiftFromRustBuffer(value);
    }
    public override RustBuffer Lower(CsType value) {
        return LowerIntoRustBuffer(value);
    }
}


// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.
// Error runtime.
[StructLayout(LayoutKind.Sequential)]
struct UniffiRustCallStatus {
    public sbyte code;
    public RustBuffer error_buf;

    public bool IsSuccess() {
        return code == 0;
    }

    public bool IsError() {
        return code == 1;
    }

    public bool IsPanic() {
        return code == 2;
    }
}

// Base class for all uniffi exceptions
public class UniffiException: System.Exception {
    public UniffiException(): base() {}
    public UniffiException(string message): base(message) {}
}

public class UndeclaredErrorException: UniffiException {
    public UndeclaredErrorException(string message): base(message) {}
}

public class PanicException: UniffiException {
    public PanicException(string message): base(message) {}
}

public class AllocationException: UniffiException {
    public AllocationException(string message): base(message) {}
}

public class InternalException: UniffiException {
    public InternalException(string message): base(message) {}
}

public class InvalidEnumException: InternalException {
    public InvalidEnumException(string message): base(message) {
    }
}

public class UniffiContractVersionException: UniffiException {
    public UniffiContractVersionException(string message): base(message) {
    }
}

public class UniffiContractChecksumException: UniffiException {
    public UniffiContractChecksumException(string message): base(message) {
    }
}

// Each top-level error class has a companion object that can lift the error from the call status's rust buffer
interface CallStatusErrorHandler<E> where E: System.Exception {
    E Lift(RustBuffer error_buf);
}

// CallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
class NullCallStatusErrorHandler: CallStatusErrorHandler<UniffiException> {
    public static NullCallStatusErrorHandler INSTANCE = new NullCallStatusErrorHandler();

    public UniffiException Lift(RustBuffer error_buf) {
        RustBuffer.Free(error_buf);
        return new UndeclaredErrorException("library has returned an error not declared in UNIFFI interface file");
    }
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself
class _UniffiHelpers {
    public delegate void RustCallAction(ref UniffiRustCallStatus status);
    public delegate U RustCallFunc<out U>(ref UniffiRustCallStatus status);

    // Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
    public static U RustCallWithError<U, E>(CallStatusErrorHandler<E> errorHandler, RustCallFunc<U> callback)
        where E: System.Exception
    {
        var status = new UniffiRustCallStatus();
        var return_value = callback(ref status);
        if (status.IsSuccess()) {
            return return_value;
        } else if (status.IsError()) {
            throw errorHandler.Lift(status.error_buf);
        } else if (status.IsPanic()) {
            // when the rust code sees a panic, it tries to construct a rustbuffer
            // with the message.  but if that code panics, then it just sends back
            // an empty buffer.
            if (status.error_buf.len > 0) {
                throw new PanicException(FfiConverterString.INSTANCE.Lift(status.error_buf));
            } else {
                throw new PanicException("Rust panic");
            }
        } else {
            throw new InternalException($"Unknown rust call status: {status.code}");
        }
    }

    // Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
    public static void RustCallWithError<E>(CallStatusErrorHandler<E> errorHandler, RustCallAction callback)
        where E: System.Exception
    {
        _UniffiHelpers.RustCallWithError(errorHandler, (ref UniffiRustCallStatus status) => {
            callback(ref status);
            return 0;
        });
    }

    // Call a rust function that returns a plain value
    public static U RustCall<U>(RustCallFunc<U> callback) {
        return _UniffiHelpers.RustCallWithError(NullCallStatusErrorHandler.INSTANCE, callback);
    }

    // Call a rust function that returns a plain value
    public static void RustCall(RustCallAction callback) {
        _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            callback(ref status);
            return 0;
        });
    }
}

static class FFIObjectUtil {
    public static void DisposeAll(params Object?[] list) {
        Dispose(list);
    }

    // Dispose is implemented by recursive type inspection at runtime. This is because
    // generating correct Dispose calls for recursive complex types, e.g. List<List<int>>
    // is quite cumbersome.
   private static void Dispose(Object? obj) {
         if (obj == null) {
             return;
         }

         if (obj is IDisposable disposable) {
             disposable.Dispose();
             return;
         }

         var objType = obj.GetType();
         var typeCode = Type.GetTypeCode(objType);
         if (typeCode != TypeCode.Object) {
             return;
         }

         var genericArguments = objType.GetGenericArguments();
         if (genericArguments.Length == 0 && !objType.IsArray) {
             return;
         }

         if (obj is System.Collections.IDictionary objDictionary) {
             //This extra code tests to not call "Dispose" for a Dictionary<something, double>()
             //for all values as "double" and alike doesn't support interface "IDisposable"
             var valuesType = objType.GetGenericArguments()[1];
             var elementValuesTypeCode = Type.GetTypeCode(valuesType);
             if (elementValuesTypeCode != TypeCode.Object) {
                 return;
             }
             foreach (var value in objDictionary.Values) {
                 Dispose(value);
             }
         }
         else if (obj is System.Collections.IEnumerable listValues) {
             //This extra code tests to not call "Dispose" for a List<int>()
             //for all keys as "int" and alike doesn't support interface "IDisposable"
             var elementType = objType.IsArray ? objType.GetElementType() : genericArguments[0];
             var elementValuesTypeCode = Type.GetTypeCode(elementType);
             if (elementValuesTypeCode != TypeCode.Object) {
                 return;
             }
             foreach (var value in listValues) {
                 Dispose(value);
             }
         }
     }
}


// Big endian streams are not yet available in dotnet :'(
// https://github.com/dotnet/runtime/issues/26904

class StreamUnderflowException: System.Exception {
    public StreamUnderflowException() {
    }
}

static class BigEndianStreamExtensions
{
    public static void WriteInt32(this Stream stream, int value, int bytesToWrite = 4)
    {
#if NET8_0_OR_GREATER
        Span<byte> buffer = stackalloc byte[bytesToWrite];
#else
        byte[] buffer = new byte[bytesToWrite];
#endif
        var posByte = bytesToWrite;
        while (posByte != 0)
        {
            posByte--;
            buffer[posByte] = (byte)(value);
            value >>= 8;
        }

#if NET8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    public static void WriteInt64(this Stream stream, long value)
    {
        int bytesToWrite = 8;
#if NET8_0_OR_GREATER
         Span<byte> buffer = stackalloc byte[bytesToWrite];
 #else
         byte[] buffer = new byte[bytesToWrite];
 #endif
        var posByte = bytesToWrite;
        while (posByte != 0)
        {
            posByte--;
            buffer[posByte] = (byte)(value);
            value >>= 8;
        }

#if NET8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    public static uint ReadUint32(this Stream stream, int bytesToRead = 4) {
        CheckRemaining(stream, bytesToRead);
#if NET8_0_OR_GREATER
         Span<byte> buffer = stackalloc byte[bytesToRead];
         stream.Read(buffer);
#else
        byte[] buffer = new byte[bytesToRead];
        stream.Read(buffer, 0, bytesToRead);
#endif
        uint result = 0;
        uint digitMultiplier = 1;
        int posByte = bytesToRead;
        while (posByte != 0)
        {
            posByte--;
            result |= buffer[posByte]*digitMultiplier;
            digitMultiplier <<= 8;
        }

        return result;
    }

    public static ulong ReadUInt64(this Stream stream) {
        int bytesToRead = 8;
        CheckRemaining(stream, bytesToRead);
#if NET8_0_OR_GREATER
         Span<byte> buffer = stackalloc byte[bytesToRead];
         stream.Read(buffer);
#else
        byte[] buffer = new byte[bytesToRead];
        stream.Read(buffer, 0, bytesToRead);
#endif
        ulong result = 0;
        ulong digitMultiplier = 1;
        int posByte = bytesToRead;
        while (posByte != 0)
        {
            posByte--;
            result |= buffer[posByte]*digitMultiplier;
            digitMultiplier <<= 8;
        }

        return result;
    }

    public static void CheckRemaining(this Stream stream, int length) {
        if (stream.Length - stream.Position < length) {
            throw new StreamUnderflowException();
        }
    }

    public static void ForEach<T>(this T[] items, Action<T> action){
        foreach (var item in items) {
            action(item);
        }
    }
}

class BigEndianStream {
    Stream stream;
    public BigEndianStream(Stream stream) {
        this.stream = stream;
    }

    public Stream InnerStream => stream;

    public bool HasRemaining() {
        return (stream.Length - Position) > 0;
    }

    public long Position {
        get => stream.Position;
        set => stream.Position = value;
    }

    public void WriteBytes(byte[] buffer) {
#if NET8_0_OR_GREATER
        stream.Write(buffer);
#else
        stream.Write(buffer, 0, buffer.Length);
#endif
    }

    public void WriteByte(byte value) => stream.WriteInt32(value, bytesToWrite: 1);
    public void WriteSByte(sbyte value) => stream.WriteInt32(value, bytesToWrite: 1);

    public void WriteUShort(ushort value) => stream.WriteInt32(value, bytesToWrite: 2);
    public void WriteShort(short value) => stream.WriteInt32(value, bytesToWrite: 2);

    public void WriteUInt(uint value) => stream.WriteInt32((int)value);
    public void WriteInt(int value) => stream.WriteInt32(value);

    public void WriteULong(ulong value) => stream.WriteInt64((long)value);
    public void WriteLong(long value) => stream.WriteInt64(value);

    public void WriteFloat(float value) {
        unsafe {
            WriteInt(*((int*)&value));
        }
    }
    public void WriteDouble(double value) => stream.WriteInt64(BitConverter.DoubleToInt64Bits(value));

    public byte[] ReadBytes(int length) {
        stream.CheckRemaining(length);
        byte[] result = new byte[length];
        stream.Read(result, 0, length);
        return result;
    }

    public byte ReadByte() => (byte)stream.ReadUint32(bytesToRead: 1);
    public ushort ReadUShort() => (ushort)stream.ReadUint32(bytesToRead: 2);
    public uint ReadUInt() => (uint)stream.ReadUint32(bytesToRead: 4);
    public ulong ReadULong() => stream.ReadUInt64();

    public sbyte ReadSByte() => (sbyte)ReadByte();
    public short ReadShort() => (short)ReadUShort();
    public int ReadInt() => (int)ReadUInt();

    public float ReadFloat() {
        unsafe {
            int value = ReadInt();
            return *((float*)&value);
        }
    }

    public long ReadLong() => (long)ReadULong();
    public double ReadDouble() => BitConverter.Int64BitsToDouble(ReadLong());
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.


// This is an implementation detail that will be called internally by the public API.
#if NET8_0_OR_GREATER
static partial class _UniFFILib {
#else
static class _UniFFILib {
#endif
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiRustFutureContinuationCallback(
        ulong @data,sbyte @pollResult
    );
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureDroppedCallback(
        ulong @handle
    );
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiCallbackInterfaceFree(
        ulong @handle
    );
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate ulong UniffiCallbackInterfaceClone(
        ulong @handle
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureDroppedCallbackStruct
    {
        public ulong @handle;
        public IntPtr @free;
    }
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultU8
    {
        public byte @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU8(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureResultU8 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultI8
    {
        public sbyte @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI8(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureResultI8 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultU16
    {
        public ushort @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU16(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureResultU16 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultI16
    {
        public short @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI16(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureResultI16 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultU32
    {
        public uint @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU32(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureResultU32 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultI32
    {
        public int @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI32(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureResultI32 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultU64
    {
        public ulong @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteU64(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureResultU64 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultI64
    {
        public long @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteI64(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureResultI64 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultF32
    {
        public float @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteF32(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureResultF32 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultF64
    {
        public double @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteF64(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureResultF64 @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultRustBuffer
    {
        public RustBuffer @returnValue;
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteRustBuffer(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureResultRustBuffer @result
    );
    [StructLayout(LayoutKind.Sequential)]
    public struct UniffiForeignFutureResultVoid
    {
        public UniffiRustCallStatus @callStatus;
    }
    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    public delegate void UniffiForeignFutureCompleteVoid(
        ulong @callbackData,_UniFFILib.UniffiForeignFutureResultVoid @result
    );
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

    static _UniFFILib() {
        _UniFFILib.uniffiCheckContractApiVersion();
        _UniFFILib.uniffiCheckApiChecksums();
        
        }

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     ulong uniffi_livekit_token_source_fn_clone_tokensourceendpoint(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void uniffi_livekit_token_source_fn_free_tokensourceendpoint(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     ulong uniffi_livekit_token_source_fn_constructor_tokensourceendpoint_new(RustBuffer @endpointUrl,RustBuffer @headerName,RustBuffer @headerValue,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     ulong uniffi_livekit_token_source_fn_method_tokensourceendpoint_fetch(ulong @ptr,RustBuffer @options
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     ulong uniffi_livekit_token_source_fn_clone_tokensourceliteral(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void uniffi_livekit_token_source_fn_free_tokensourceliteral(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     ulong uniffi_livekit_token_source_fn_constructor_tokensourceliteral_new(RustBuffer @response,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     RustBuffer uniffi_livekit_token_source_fn_method_tokensourceliteral_fetch(ulong @ptr,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     ulong uniffi_livekit_token_source_fn_clone_tokensourcesandbox(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void uniffi_livekit_token_source_fn_free_tokensourcesandbox(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     ulong uniffi_livekit_token_source_fn_constructor_tokensourcesandbox_new(RustBuffer @sandboxId,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     ulong uniffi_livekit_token_source_fn_method_tokensourcesandbox_fetch(ulong @ptr,RustBuffer @options
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     RustBuffer ffi_livekit_token_source_rustbuffer_alloc(ulong @size,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     RustBuffer ffi_livekit_token_source_rustbuffer_from_bytes(ForeignBytes @bytes,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rustbuffer_free(RustBuffer @buf,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     RustBuffer ffi_livekit_token_source_rustbuffer_reserve(RustBuffer @buf,ulong @additional,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rust_future_poll_u8(ulong @handle,IntPtr @callback,ulong @callbackData
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rust_future_cancel_u8(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rust_future_free_u8(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     byte ffi_livekit_token_source_rust_future_complete_u8(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rust_future_poll_i8(ulong @handle,IntPtr @callback,ulong @callbackData
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rust_future_cancel_i8(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rust_future_free_i8(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     sbyte ffi_livekit_token_source_rust_future_complete_i8(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rust_future_poll_u16(ulong @handle,IntPtr @callback,ulong @callbackData
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rust_future_cancel_u16(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rust_future_free_u16(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     ushort ffi_livekit_token_source_rust_future_complete_u16(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rust_future_poll_i16(ulong @handle,IntPtr @callback,ulong @callbackData
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rust_future_cancel_i16(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rust_future_free_i16(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     short ffi_livekit_token_source_rust_future_complete_i16(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rust_future_poll_u32(ulong @handle,IntPtr @callback,ulong @callbackData
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rust_future_cancel_u32(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rust_future_free_u32(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     uint ffi_livekit_token_source_rust_future_complete_u32(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rust_future_poll_i32(ulong @handle,IntPtr @callback,ulong @callbackData
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rust_future_cancel_i32(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rust_future_free_i32(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     int ffi_livekit_token_source_rust_future_complete_i32(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rust_future_poll_u64(ulong @handle,IntPtr @callback,ulong @callbackData
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rust_future_cancel_u64(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rust_future_free_u64(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     ulong ffi_livekit_token_source_rust_future_complete_u64(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rust_future_poll_i64(ulong @handle,IntPtr @callback,ulong @callbackData
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rust_future_cancel_i64(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rust_future_free_i64(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     long ffi_livekit_token_source_rust_future_complete_i64(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rust_future_poll_f32(ulong @handle,IntPtr @callback,ulong @callbackData
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rust_future_cancel_f32(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rust_future_free_f32(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     float ffi_livekit_token_source_rust_future_complete_f32(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rust_future_poll_f64(ulong @handle,IntPtr @callback,ulong @callbackData
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rust_future_cancel_f64(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rust_future_free_f64(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     double ffi_livekit_token_source_rust_future_complete_f64(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rust_future_poll_rust_buffer(ulong @handle,IntPtr @callback,ulong @callbackData
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rust_future_cancel_rust_buffer(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rust_future_free_rust_buffer(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     RustBuffer ffi_livekit_token_source_rust_future_complete_rust_buffer(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rust_future_poll_void(ulong @handle,IntPtr @callback,ulong @callbackData
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rust_future_cancel_void(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rust_future_free_void(ulong @handle
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     void ffi_livekit_token_source_rust_future_complete_void(ulong @handle,ref UniffiRustCallStatus _uniffi_out_err
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     ushort uniffi_livekit_token_source_checksum_method_tokensourceendpoint_fetch(
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     ushort uniffi_livekit_token_source_checksum_method_tokensourceliteral_fetch(
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     ushort uniffi_livekit_token_source_checksum_method_tokensourcesandbox_fetch(
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     ushort uniffi_livekit_token_source_checksum_constructor_tokensourceendpoint_new(
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     ushort uniffi_livekit_token_source_checksum_constructor_tokensourceliteral_new(
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     ushort uniffi_livekit_token_source_checksum_constructor_tokensourcesandbox_new(
    );

    #if NET8_0_OR_GREATER
    [LibraryImport("livekit_token_source")]
    [UnmanagedCallConv(CallConvs = new[] { typeof(CallConvCdecl) })]
    public static partial
#else
    [DllImport("livekit_token_source", CallingConvention = CallingConvention.Cdecl)]
    public static extern
#endif
     uint ffi_livekit_token_source_uniffi_contract_version(
    );

    

    static void uniffiCheckContractApiVersion() {
        var scaffolding_contract_version = _UniFFILib.ffi_livekit_token_source_uniffi_contract_version();
        if (30 != scaffolding_contract_version) {
            throw new UniffiContractVersionException($"uniffi.livekit_token_source: uniffi bindings expected version `30`, library returned `{scaffolding_contract_version}`");
        }
    }
    static void uniffiCheckApiChecksums() {
        {
            var checksum = _UniFFILib.uniffi_livekit_token_source_checksum_method_tokensourceendpoint_fetch();
            if (checksum != 6701) {
                throw new UniffiContractChecksumException($"uniffi.livekit_token_source: uniffi bindings expected function `uniffi_livekit_token_source_checksum_method_tokensourceendpoint_fetch` checksum `6701`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_livekit_token_source_checksum_method_tokensourceliteral_fetch();
            if (checksum != 31613) {
                throw new UniffiContractChecksumException($"uniffi.livekit_token_source: uniffi bindings expected function `uniffi_livekit_token_source_checksum_method_tokensourceliteral_fetch` checksum `31613`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_livekit_token_source_checksum_method_tokensourcesandbox_fetch();
            if (checksum != 50228) {
                throw new UniffiContractChecksumException($"uniffi.livekit_token_source: uniffi bindings expected function `uniffi_livekit_token_source_checksum_method_tokensourcesandbox_fetch` checksum `50228`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_livekit_token_source_checksum_constructor_tokensourceendpoint_new();
            if (checksum != 9755) {
                throw new UniffiContractChecksumException($"uniffi.livekit_token_source: uniffi bindings expected function `uniffi_livekit_token_source_checksum_constructor_tokensourceendpoint_new` checksum `9755`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_livekit_token_source_checksum_constructor_tokensourceliteral_new();
            if (checksum != 25947) {
                throw new UniffiContractChecksumException($"uniffi.livekit_token_source: uniffi bindings expected function `uniffi_livekit_token_source_checksum_constructor_tokensourceliteral_new` checksum `25947`, library returned `{checksum}`");
            }
        }
        {
            var checksum = _UniFFILib.uniffi_livekit_token_source_checksum_constructor_tokensourcesandbox_new();
            if (checksum != 49664) {
                throw new UniffiContractChecksumException($"uniffi.livekit_token_source: uniffi bindings expected function `uniffi_livekit_token_source_checksum_constructor_tokensourcesandbox_new` checksum `49664`, library returned `{checksum}`");
            }
        }
    }
}

// Public interface members begin here.

#pragma warning disable 8625




class FfiConverterUInt16: FfiConverter<ushort, ushort> {
    public static FfiConverterUInt16 INSTANCE = new FfiConverterUInt16();

    public override ushort Lift(ushort value) {
        return value;
    }

    public override ushort Read(BigEndianStream stream) {
        return stream.ReadUShort();
    }

    public override ushort Lower(ushort value) {
        return value;
    }

    public override int AllocationSize(ushort value) {
        return 2;
    }

    public override void Write(ushort value, BigEndianStream stream) {
        stream.WriteUShort(value);
    }
}



class FfiConverterString: FfiConverter<string, RustBuffer> {
    public static FfiConverterString INSTANCE = new FfiConverterString();

    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    public override string Lift(RustBuffer value) {
        try {
            var bytes = value.AsStream().ReadBytes(Convert.ToInt32(value.len));
            return System.Text.Encoding.UTF8.GetString(bytes);
        } finally {
            RustBuffer.Free(value);
        }
    }

    public override string Read(BigEndianStream stream) {
        var length = stream.ReadInt();
        var bytes = stream.ReadBytes(length);
        return System.Text.Encoding.UTF8.GetString(bytes);
    }

    public override RustBuffer Lower(string value) {
        var bytes = System.Text.Encoding.UTF8.GetBytes(value);
        var rbuf = RustBuffer.Alloc(bytes.Length);
        rbuf.AsWriteableStream().WriteBytes(bytes);
        return rbuf;
    }

    // TODO(CS)
    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per unicode codepoint which will always be
    // enough.
    public override int AllocationSize(string value) {
        const int sizeForLength = 4;
        var sizeForString = System.Text.Encoding.UTF8.GetByteCount(value);
        return sizeForLength + sizeForString;
    }

    public override void Write(string value, BigEndianStream stream) {
        var bytes = System.Text.Encoding.UTF8.GetBytes(value);
        stream.WriteInt(bytes.Length);
        stream.WriteBytes(bytes);
    }
}



public interface ITokenSourceEndpoint {
    /// <exception cref="TokenSourceException"></exception>
    Task<TokenSourceResponse> Fetch(TokenSourceFetchOptions @options);
}
public class TokenSourceEndpoint : ITokenSourceEndpoint, IDisposable {
    protected ulong pointer;
    private int _wasDestroyed = 0;
    private long _callCounter = 1;

    public TokenSourceEndpoint(ulong pointer) {
        this.pointer = pointer;
    }

    ~TokenSourceEndpoint() {
        Destroy();
    }
    public TokenSourceEndpoint(string @endpointUrl, string @headerName, string @headerValue) :
        this(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_livekit_token_source_fn_constructor_tokensourceendpoint_new(FfiConverterString.INSTANCE.Lower(@endpointUrl), FfiConverterString.INSTANCE.Lower(@headerName), FfiConverterString.INSTANCE.Lower(@headerValue), ref _status)
)) {}

    protected void FreeRustArcPtr() {
        _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            _UniFFILib.uniffi_livekit_token_source_fn_free_tokensourceendpoint(this.pointer, ref status);
        });
    }

    protected ulong CloneRustArcPtr() {
        return _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            return _UniFFILib.uniffi_livekit_token_source_fn_clone_tokensourceendpoint(this.pointer, ref status);
        });
    }

    public void Destroy()
    {
        // Only allow a single call to this method.
        if (Interlocked.CompareExchange(ref _wasDestroyed, 1, 0) == 0)
        {
            // This decrement always matches the initial count of 1 given at creation time.
            if (Interlocked.Decrement(ref _callCounter) == 0)
            {
                FreeRustArcPtr();
            }
        }
    }

    public void Dispose()
    {
        Destroy();
        GC.SuppressFinalize(this); // Suppress finalization to avoid unnecessary GC overhead.
    }

    private void IncrementCallCounter() 
    {
        // Check and increment the call counter, to keep the object alive.
        // This needs a compare-and-set retry loop in case of concurrent updates.
        long count;
        do
        {
            count = Interlocked.Read(ref _callCounter);
            if (count == 0L) throw new System.ObjectDisposedException(String.Format("'{0}' object has already been destroyed", this.GetType().Name));
            if (count == long.MaxValue) throw new System.OverflowException(String.Format("'{0}' call counter would overflow", this.GetType().Name));

        } while (Interlocked.CompareExchange(ref _callCounter, count + 1, count) != count);
    }

    private void DecrementCallCounter() 
    {
        // This decrement always matches the increment we performed above.
        if (Interlocked.Decrement(ref _callCounter) == 0) {
            FreeRustArcPtr();
        }
    }

    internal void CallWithPointer(Action<ulong> action)
    {
        IncrementCallCounter();
        try {
            action(CloneRustArcPtr());
        }
        finally {
            DecrementCallCounter();
        }
    }

    internal T CallWithPointer<T>(Func<ulong, T> func)
    {   
        IncrementCallCounter();
        try {
            return func(CloneRustArcPtr());
        }
        finally {
            DecrementCallCounter();
        }
    }

    
    /// <exception cref="TokenSourceException"></exception>
    public async Task<TokenSourceResponse> Fetch(TokenSourceFetchOptions @options) {
    return await _UniFFIAsync.UniffiRustCallAsync(
        // Get rust future
        CallWithPointer(thisPtr => {
            return _UniFFILib.uniffi_livekit_token_source_fn_method_tokensourceendpoint_fetch(thisPtr, FfiConverterTypeTokenSourceFetchOptions.INSTANCE.Lower(@options));
        }),
        // Poll
        (ulong future, IntPtr continuation, ulong data) => _UniFFILib.ffi_livekit_token_source_rust_future_poll_rust_buffer(future, continuation, data),
        // Complete
        (ulong future, ref UniffiRustCallStatus status) => {
            return _UniFFILib.ffi_livekit_token_source_rust_future_complete_rust_buffer(future, ref status);
        },
        // Free
        (ulong future) => _UniFFILib.ffi_livekit_token_source_rust_future_free_rust_buffer(future),
        // Lift
        (result) => FfiConverterTypeTokenSourceResponse.INSTANCE.Lift(result),
        // Error
        FfiConverterTypeTokenSourceError.INSTANCE
    );
    }
    

    
}
class FfiConverterTypeTokenSourceEndpoint: FfiConverter<TokenSourceEndpoint, ulong> {
    public static FfiConverterTypeTokenSourceEndpoint INSTANCE = new FfiConverterTypeTokenSourceEndpoint();


    public override ulong Lower(TokenSourceEndpoint value) {
        return value.CallWithPointer(thisPtr => thisPtr);
    }

    public override TokenSourceEndpoint Lift(ulong value) {
        return new TokenSourceEndpoint(value);
    }

    public override TokenSourceEndpoint Read(BigEndianStream stream) {
        return Lift(stream.ReadULong());
    }

    public override int AllocationSize(TokenSourceEndpoint value) {
        return 8;
    }

    public override void Write(TokenSourceEndpoint value, BigEndianStream stream) {
        stream.WriteULong(Lower(value));
    }
}



public interface ITokenSourceLiteral {
    /// <exception cref="TokenSourceException"></exception>
    TokenSourceResponse Fetch();
}
public class TokenSourceLiteral : ITokenSourceLiteral, IDisposable {
    protected ulong pointer;
    private int _wasDestroyed = 0;
    private long _callCounter = 1;

    public TokenSourceLiteral(ulong pointer) {
        this.pointer = pointer;
    }

    ~TokenSourceLiteral() {
        Destroy();
    }
    public TokenSourceLiteral(TokenSourceResponse @response) :
        this(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_livekit_token_source_fn_constructor_tokensourceliteral_new(FfiConverterTypeTokenSourceResponse.INSTANCE.Lower(@response), ref _status)
)) {}

    protected void FreeRustArcPtr() {
        _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            _UniFFILib.uniffi_livekit_token_source_fn_free_tokensourceliteral(this.pointer, ref status);
        });
    }

    protected ulong CloneRustArcPtr() {
        return _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            return _UniFFILib.uniffi_livekit_token_source_fn_clone_tokensourceliteral(this.pointer, ref status);
        });
    }

    public void Destroy()
    {
        // Only allow a single call to this method.
        if (Interlocked.CompareExchange(ref _wasDestroyed, 1, 0) == 0)
        {
            // This decrement always matches the initial count of 1 given at creation time.
            if (Interlocked.Decrement(ref _callCounter) == 0)
            {
                FreeRustArcPtr();
            }
        }
    }

    public void Dispose()
    {
        Destroy();
        GC.SuppressFinalize(this); // Suppress finalization to avoid unnecessary GC overhead.
    }

    private void IncrementCallCounter() 
    {
        // Check and increment the call counter, to keep the object alive.
        // This needs a compare-and-set retry loop in case of concurrent updates.
        long count;
        do
        {
            count = Interlocked.Read(ref _callCounter);
            if (count == 0L) throw new System.ObjectDisposedException(String.Format("'{0}' object has already been destroyed", this.GetType().Name));
            if (count == long.MaxValue) throw new System.OverflowException(String.Format("'{0}' call counter would overflow", this.GetType().Name));

        } while (Interlocked.CompareExchange(ref _callCounter, count + 1, count) != count);
    }

    private void DecrementCallCounter() 
    {
        // This decrement always matches the increment we performed above.
        if (Interlocked.Decrement(ref _callCounter) == 0) {
            FreeRustArcPtr();
        }
    }

    internal void CallWithPointer(Action<ulong> action)
    {
        IncrementCallCounter();
        try {
            action(CloneRustArcPtr());
        }
        finally {
            DecrementCallCounter();
        }
    }

    internal T CallWithPointer<T>(Func<ulong, T> func)
    {   
        IncrementCallCounter();
        try {
            return func(CloneRustArcPtr());
        }
        finally {
            DecrementCallCounter();
        }
    }

    
    /// <exception cref="TokenSourceException"></exception>
    public TokenSourceResponse Fetch() {
        return CallWithPointer(thisPtr => FfiConverterTypeTokenSourceResponse.INSTANCE.Lift(
    _UniffiHelpers.RustCallWithError(FfiConverterTypeTokenSourceError.INSTANCE, (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_livekit_token_source_fn_method_tokensourceliteral_fetch(thisPtr,  ref _status)
)));
    }
    
    

    
}
class FfiConverterTypeTokenSourceLiteral: FfiConverter<TokenSourceLiteral, ulong> {
    public static FfiConverterTypeTokenSourceLiteral INSTANCE = new FfiConverterTypeTokenSourceLiteral();


    public override ulong Lower(TokenSourceLiteral value) {
        return value.CallWithPointer(thisPtr => thisPtr);
    }

    public override TokenSourceLiteral Lift(ulong value) {
        return new TokenSourceLiteral(value);
    }

    public override TokenSourceLiteral Read(BigEndianStream stream) {
        return Lift(stream.ReadULong());
    }

    public override int AllocationSize(TokenSourceLiteral value) {
        return 8;
    }

    public override void Write(TokenSourceLiteral value, BigEndianStream stream) {
        stream.WriteULong(Lower(value));
    }
}



public interface ITokenSourceSandbox {
    /// <exception cref="TokenSourceException"></exception>
    Task<TokenSourceResponse> Fetch(TokenSourceFetchOptions @options);
}
public class TokenSourceSandbox : ITokenSourceSandbox, IDisposable {
    protected ulong pointer;
    private int _wasDestroyed = 0;
    private long _callCounter = 1;

    public TokenSourceSandbox(ulong pointer) {
        this.pointer = pointer;
    }

    ~TokenSourceSandbox() {
        Destroy();
    }
    public TokenSourceSandbox(string @sandboxId) :
        this(
    _UniffiHelpers.RustCall( (ref UniffiRustCallStatus _status) =>
    _UniFFILib.uniffi_livekit_token_source_fn_constructor_tokensourcesandbox_new(FfiConverterString.INSTANCE.Lower(@sandboxId), ref _status)
)) {}

    protected void FreeRustArcPtr() {
        _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            _UniFFILib.uniffi_livekit_token_source_fn_free_tokensourcesandbox(this.pointer, ref status);
        });
    }

    protected ulong CloneRustArcPtr() {
        return _UniffiHelpers.RustCall((ref UniffiRustCallStatus status) => {
            return _UniFFILib.uniffi_livekit_token_source_fn_clone_tokensourcesandbox(this.pointer, ref status);
        });
    }

    public void Destroy()
    {
        // Only allow a single call to this method.
        if (Interlocked.CompareExchange(ref _wasDestroyed, 1, 0) == 0)
        {
            // This decrement always matches the initial count of 1 given at creation time.
            if (Interlocked.Decrement(ref _callCounter) == 0)
            {
                FreeRustArcPtr();
            }
        }
    }

    public void Dispose()
    {
        Destroy();
        GC.SuppressFinalize(this); // Suppress finalization to avoid unnecessary GC overhead.
    }

    private void IncrementCallCounter() 
    {
        // Check and increment the call counter, to keep the object alive.
        // This needs a compare-and-set retry loop in case of concurrent updates.
        long count;
        do
        {
            count = Interlocked.Read(ref _callCounter);
            if (count == 0L) throw new System.ObjectDisposedException(String.Format("'{0}' object has already been destroyed", this.GetType().Name));
            if (count == long.MaxValue) throw new System.OverflowException(String.Format("'{0}' call counter would overflow", this.GetType().Name));

        } while (Interlocked.CompareExchange(ref _callCounter, count + 1, count) != count);
    }

    private void DecrementCallCounter() 
    {
        // This decrement always matches the increment we performed above.
        if (Interlocked.Decrement(ref _callCounter) == 0) {
            FreeRustArcPtr();
        }
    }

    internal void CallWithPointer(Action<ulong> action)
    {
        IncrementCallCounter();
        try {
            action(CloneRustArcPtr());
        }
        finally {
            DecrementCallCounter();
        }
    }

    internal T CallWithPointer<T>(Func<ulong, T> func)
    {   
        IncrementCallCounter();
        try {
            return func(CloneRustArcPtr());
        }
        finally {
            DecrementCallCounter();
        }
    }

    
    /// <exception cref="TokenSourceException"></exception>
    public async Task<TokenSourceResponse> Fetch(TokenSourceFetchOptions @options) {
    return await _UniFFIAsync.UniffiRustCallAsync(
        // Get rust future
        CallWithPointer(thisPtr => {
            return _UniFFILib.uniffi_livekit_token_source_fn_method_tokensourcesandbox_fetch(thisPtr, FfiConverterTypeTokenSourceFetchOptions.INSTANCE.Lower(@options));
        }),
        // Poll
        (ulong future, IntPtr continuation, ulong data) => _UniFFILib.ffi_livekit_token_source_rust_future_poll_rust_buffer(future, continuation, data),
        // Complete
        (ulong future, ref UniffiRustCallStatus status) => {
            return _UniFFILib.ffi_livekit_token_source_rust_future_complete_rust_buffer(future, ref status);
        },
        // Free
        (ulong future) => _UniFFILib.ffi_livekit_token_source_rust_future_free_rust_buffer(future),
        // Lift
        (result) => FfiConverterTypeTokenSourceResponse.INSTANCE.Lift(result),
        // Error
        FfiConverterTypeTokenSourceError.INSTANCE
    );
    }
    

    
}
class FfiConverterTypeTokenSourceSandbox: FfiConverter<TokenSourceSandbox, ulong> {
    public static FfiConverterTypeTokenSourceSandbox INSTANCE = new FfiConverterTypeTokenSourceSandbox();


    public override ulong Lower(TokenSourceSandbox value) {
        return value.CallWithPointer(thisPtr => thisPtr);
    }

    public override TokenSourceSandbox Lift(ulong value) {
        return new TokenSourceSandbox(value);
    }

    public override TokenSourceSandbox Read(BigEndianStream stream) {
        return Lift(stream.ReadULong());
    }

    public override int AllocationSize(TokenSourceSandbox value) {
        return 8;
    }

    public override void Write(TokenSourceSandbox value, BigEndianStream stream) {
        stream.WriteULong(Lower(value));
    }
}



/// <summary>
/// Per-call overrides used to parameterize a token request.
///
/// Every field is optional: `None` means "leave it out of the request" and the
/// server picks a default. Because the struct derives `Default`, you only need
/// to set the fields you care about:
///
/// ```
/// TokenSourceFetchOptions {
/// room_name: Some("my-room".to_string()),
/// ..Default::default()
/// };
/// ```
/// </summary>
/// <param name="RoomName">
/// The name of the room being requested when generating credentials.
/// </param>
/// <param name="ParticipantName">
/// The name of the participant being requested when generating credentials.
/// </param>
/// <param name="ParticipantIdentity">
/// The identity of the participant being requested when generating credentials.
/// </param>
/// <param name="ParticipantMetadata">
/// The metadata of the participant being requested when generating credentials.
/// </param>
/// <param name="ParticipantAttributes">
/// The attributes of the participant being requested when generating credentials.
/// </param>
/// <param name="AgentName">
/// The name of the agent to dispatch into the room.
/// </param>
/// <param name="AgentMetadata">
/// The metadata to pass to the dispatched agent.
/// </param>
/// <param name="AgentDeployment">
/// Optional deployment to target. Leave empty to target the production deployment.
/// </param>
public record TokenSourceFetchOptions (
    /// <summary>
    /// The name of the room being requested when generating credentials.
    /// </summary>
    string? RoomName = null, 
    /// <summary>
    /// The name of the participant being requested when generating credentials.
    /// </summary>
    string? ParticipantName = null, 
    /// <summary>
    /// The identity of the participant being requested when generating credentials.
    /// </summary>
    string? ParticipantIdentity = null, 
    /// <summary>
    /// The metadata of the participant being requested when generating credentials.
    /// </summary>
    string? ParticipantMetadata = null, 
    /// <summary>
    /// The attributes of the participant being requested when generating credentials.
    /// </summary>
    Dictionary<string, string>? ParticipantAttributes = null, 
    /// <summary>
    /// The name of the agent to dispatch into the room.
    /// </summary>
    string? AgentName = null, 
    /// <summary>
    /// The metadata to pass to the dispatched agent.
    /// </summary>
    string? AgentMetadata = null, 
    /// <summary>
    /// Optional deployment to target. Leave empty to target the production deployment.
    /// </summary>
    string? AgentDeployment = null
) {
}

class FfiConverterTypeTokenSourceFetchOptions: FfiConverterRustBuffer<TokenSourceFetchOptions> {
    public static FfiConverterTypeTokenSourceFetchOptions INSTANCE = new FfiConverterTypeTokenSourceFetchOptions();

    public override TokenSourceFetchOptions Read(BigEndianStream stream) {
        return new TokenSourceFetchOptions(
            RoomName: FfiConverterOptionalString.INSTANCE.Read(stream),
            ParticipantName: FfiConverterOptionalString.INSTANCE.Read(stream),
            ParticipantIdentity: FfiConverterOptionalString.INSTANCE.Read(stream),
            ParticipantMetadata: FfiConverterOptionalString.INSTANCE.Read(stream),
            ParticipantAttributes: FfiConverterOptionalDictionaryStringString.INSTANCE.Read(stream),
            AgentName: FfiConverterOptionalString.INSTANCE.Read(stream),
            AgentMetadata: FfiConverterOptionalString.INSTANCE.Read(stream),
            AgentDeployment: FfiConverterOptionalString.INSTANCE.Read(stream)
        );
    }

    public override int AllocationSize(TokenSourceFetchOptions value) {
        return 0
            + FfiConverterOptionalString.INSTANCE.AllocationSize(value.RoomName)
            + FfiConverterOptionalString.INSTANCE.AllocationSize(value.ParticipantName)
            + FfiConverterOptionalString.INSTANCE.AllocationSize(value.ParticipantIdentity)
            + FfiConverterOptionalString.INSTANCE.AllocationSize(value.ParticipantMetadata)
            + FfiConverterOptionalDictionaryStringString.INSTANCE.AllocationSize(value.ParticipantAttributes)
            + FfiConverterOptionalString.INSTANCE.AllocationSize(value.AgentName)
            + FfiConverterOptionalString.INSTANCE.AllocationSize(value.AgentMetadata)
            + FfiConverterOptionalString.INSTANCE.AllocationSize(value.AgentDeployment);
    }

    public override void Write(TokenSourceFetchOptions value, BigEndianStream stream) {
            FfiConverterOptionalString.INSTANCE.Write(value.RoomName, stream);
            FfiConverterOptionalString.INSTANCE.Write(value.ParticipantName, stream);
            FfiConverterOptionalString.INSTANCE.Write(value.ParticipantIdentity, stream);
            FfiConverterOptionalString.INSTANCE.Write(value.ParticipantMetadata, stream);
            FfiConverterOptionalDictionaryStringString.INSTANCE.Write(value.ParticipantAttributes, stream);
            FfiConverterOptionalString.INSTANCE.Write(value.AgentName, stream);
            FfiConverterOptionalString.INSTANCE.Write(value.AgentMetadata, stream);
            FfiConverterOptionalString.INSTANCE.Write(value.AgentDeployment, stream);
    }
}



public record TokenSourceResponse (
    string ServerUrl, 
    string ParticipantToken
) {
}

class FfiConverterTypeTokenSourceResponse: FfiConverterRustBuffer<TokenSourceResponse> {
    public static FfiConverterTypeTokenSourceResponse INSTANCE = new FfiConverterTypeTokenSourceResponse();

    public override TokenSourceResponse Read(BigEndianStream stream) {
        return new TokenSourceResponse(
            ServerUrl: FfiConverterString.INSTANCE.Read(stream),
            ParticipantToken: FfiConverterString.INSTANCE.Read(stream)
        );
    }

    public override int AllocationSize(TokenSourceResponse value) {
        return 0
            + FfiConverterString.INSTANCE.AllocationSize(value.ServerUrl)
            + FfiConverterString.INSTANCE.AllocationSize(value.ParticipantToken);
    }

    public override void Write(TokenSourceResponse value, BigEndianStream stream) {
            FfiConverterString.INSTANCE.Write(value.ServerUrl, stream);
            FfiConverterString.INSTANCE.Write(value.ParticipantToken, stream);
    }
}





public class TokenSourceException: UniffiException {
    TokenSourceException() : base() {}
    TokenSourceException(String @Message) : base(@Message) {}

    // Each variant is a nested class
    
    
    public class Request : TokenSourceException {
        // Members
        public string @message;

        // Constructor
        public Request(
                string @message) : base(
                "@message" + "=" + @message) {

            this.@message = @message;
        }
    }
    
    
    public class Server : TokenSourceException {
        // Members
        public ushort @status;
        public string @body;

        // Constructor
        public Server(
                ushort @status, 
                string @body) : base(
                "@status" + "=" + @status+ ", " +
                "@body" + "=" + @body) {

            this.@status = @status;

            this.@body = @body;
        }
    }
    
    public class ErrorA : TokenSourceException {
        public ErrorA() : base() {}
    }
    
    
    public class ErrorB : TokenSourceException {
        public ErrorB() : base() {}
    }
    
    

    
}

class FfiConverterTypeTokenSourceError : FfiConverterRustBuffer<TokenSourceException>, CallStatusErrorHandler<TokenSourceException> {
    public static FfiConverterTypeTokenSourceError INSTANCE = new FfiConverterTypeTokenSourceError();

    public override TokenSourceException Read(BigEndianStream stream) {
        var value = stream.ReadInt();
        switch (value) {
            case 1:
                return new TokenSourceException.Request(
                    FfiConverterString.INSTANCE.Read(stream));
            case 2:
                return new TokenSourceException.Server(
                    FfiConverterUInt16.INSTANCE.Read(stream),
                    FfiConverterString.INSTANCE.Read(stream));
            case 3:
                return new TokenSourceException.ErrorA();
            case 4:
                return new TokenSourceException.ErrorB();
            default:
                throw new InternalException(String.Format("invalid error value '{0}' in FfiConverterTypeTokenSourceError.Read()", value));
        }
    }

    public override int AllocationSize(TokenSourceException value) {
        switch (value) {

            case TokenSourceException.Request variant_value:
                return 4
                    + FfiConverterString.INSTANCE.AllocationSize(variant_value.@message);

            case TokenSourceException.Server variant_value:
                return 4
                    + FfiConverterUInt16.INSTANCE.AllocationSize(variant_value.@status)
                    + FfiConverterString.INSTANCE.AllocationSize(variant_value.@body);

            case TokenSourceException.ErrorA variant_value:
                return 4;

            case TokenSourceException.ErrorB variant_value:
                return 4;
            default:
                throw new InternalException(String.Format("invalid error value '{0}' in FfiConverterTypeTokenSourceError.AllocationSize()", value));
        }
    }

    public override void Write(TokenSourceException value, BigEndianStream stream) {
        switch (value) {
            case TokenSourceException.Request variant_value:
                stream.WriteInt(1);
                FfiConverterString.INSTANCE.Write(variant_value.@message, stream);
                break;
            case TokenSourceException.Server variant_value:
                stream.WriteInt(2);
                FfiConverterUInt16.INSTANCE.Write(variant_value.@status, stream);
                FfiConverterString.INSTANCE.Write(variant_value.@body, stream);
                break;
            case TokenSourceException.ErrorA variant_value:
                stream.WriteInt(3);
                break;
            case TokenSourceException.ErrorB variant_value:
                stream.WriteInt(4);
                break;
            default:
                throw new InternalException(String.Format("invalid error value '{0}' in FfiConverterTypeTokenSourceError.Write()", value));
        }
    }
}




class FfiConverterOptionalString: FfiConverterRustBuffer<string?> {
    public static FfiConverterOptionalString INSTANCE = new FfiConverterOptionalString();

    public override string? Read(BigEndianStream stream) {
        if (stream.ReadByte() == 0) {
            return null;
        }
        return FfiConverterString.INSTANCE.Read(stream);
    }

    public override int AllocationSize(string? value) {
        if (value == null) {
            return 1;
        } else {
            return 1 + FfiConverterString.INSTANCE.AllocationSize((string)value);
        }
    }

    public override void Write(string? value, BigEndianStream stream) {
        if (value == null) {
            stream.WriteByte(0);
        } else {
            stream.WriteByte(1);
            FfiConverterString.INSTANCE.Write((string)value, stream);
        }
    }
}




class FfiConverterOptionalDictionaryStringString: FfiConverterRustBuffer<Dictionary<string, string>?> {
    public static FfiConverterOptionalDictionaryStringString INSTANCE = new FfiConverterOptionalDictionaryStringString();

    public override Dictionary<string, string>? Read(BigEndianStream stream) {
        if (stream.ReadByte() == 0) {
            return null;
        }
        return FfiConverterDictionaryStringString.INSTANCE.Read(stream);
    }

    public override int AllocationSize(Dictionary<string, string>? value) {
        if (value == null) {
            return 1;
        } else {
            return 1 + FfiConverterDictionaryStringString.INSTANCE.AllocationSize((Dictionary<string, string>)value);
        }
    }

    public override void Write(Dictionary<string, string>? value, BigEndianStream stream) {
        if (value == null) {
            stream.WriteByte(0);
        } else {
            stream.WriteByte(1);
            FfiConverterDictionaryStringString.INSTANCE.Write((Dictionary<string, string>)value, stream);
        }
    }
}




class FfiConverterDictionaryStringString: FfiConverterRustBuffer<Dictionary<string, string>> {
    public static FfiConverterDictionaryStringString INSTANCE = new FfiConverterDictionaryStringString();

    public override Dictionary<string, string> Read(BigEndianStream stream) {
        var len = stream.ReadInt();
        var result = new Dictionary<string, string>(len);
        Func<BigEndianStream, string> readerKey = FfiConverterString.INSTANCE.Read;
        Func<BigEndianStream, string> readerValue = FfiConverterString.INSTANCE.Read;
        for (int i = 0; i < len; i++) {
            var key = readerKey(stream);
            var value = readerValue(stream);
            result[key] = value;
        }

        return result;
    }

    public override int AllocationSize(Dictionary<string, string> value) {
        var sizeForLength = 4;

        // details/1-empty-list-as-default-method-parameter.md
        if (value == null) {
            return sizeForLength;
        }

        Func<string, int> allocationKeySizeFn = FfiConverterString.INSTANCE.AllocationSize;
        Func<string, int> allocationKValueSizeFn = FfiConverterString.INSTANCE.AllocationSize;
        var sizeForItems = value.Sum(item => allocationKeySizeFn(item.Key) + allocationKValueSizeFn(item.Value));
        return sizeForLength + sizeForItems;
    }

    public override void Write(Dictionary<string, string> value, BigEndianStream stream) {
        // details/1-empty-list-as-default-method-parameter.md
        if (value == null) {
            stream.WriteInt(0);
            return;
        }

        stream.WriteInt(value.Count);
        Action<string, BigEndianStream> writerKey = FfiConverterString.INSTANCE.Write;
        Action<string, BigEndianStream> writerValue = FfiConverterString.INSTANCE.Write;
        foreach (var item in value) {
            writerKey(item.Key, stream);
            writerValue(item.Value, stream);
        }
    }
}





class ConcurrentHandleMap<T> where T: notnull {
    readonly ConcurrentDictionary<ulong, T> _map = new();

    // Handles are odd numbers (1, 3, 5, ...) — the lowest bit must always be set.
    // Rust uses (handle & 1) to distinguish foreign-language handles from Rust Arc
    // pointers, which are always even due to memory alignment. See uniffi_core/src/ffi/handle.rs.
    const long HANDLE_INITIAL = 1;
    const long HANDLE_DELTA = 2;
    long _currentHandle = HANDLE_INITIAL - HANDLE_DELTA;

    public ulong Insert(T obj) {
        var handle = (ulong)Interlocked.Add(ref _currentHandle, HANDLE_DELTA);
        if (!_map.TryAdd(handle, obj)) {
            throw new InternalException("ConcurrentHandleMap: Duplicate handle");
        }
        return handle;
    }

    public bool TryGet(ulong handle, [NotNullWhen(true)] out T? result) {
        return _map.TryGetValue(handle, out result);
    }

    public T Get(ulong handle) {
        if (_map.TryGetValue(handle, out var result)) {
            return result;
        } else {
            throw new InternalException("ConcurrentHandleMap: Invalid handle");
        }
    }

    public bool Remove(ulong handle) {
        return _map.TryRemove(handle, out _);
    }

    public bool Remove(ulong handle, [NotNullWhen(true)] out T? result) {
        return _map.TryRemove(handle, out result);
    }
}

[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
delegate void UniFfiFutureCallback(ulong continuationHandle, byte pollResult);

internal sealed class UniffiForeignFutureHandle : System.IDisposable {
    internal CancellationTokenSource Cts { get; } = new CancellationTokenSource();
#if NET9_0_OR_GREATER
    private readonly Lock _lock = new Lock();
#else
    private readonly object _lock = new object();
#endif

    internal void MarkDropped() {
        lock (_lock) {
            if (!_callbackInvoked) { Cts.Cancel(); }
        }
    }

    private bool _callbackInvoked = false;

    internal void InvokeCallbackOnce(Action invoke) {
        bool shouldInvoke;
        lock (_lock) {
            shouldInvoke = !_callbackInvoked;
            if (shouldInvoke) _callbackInvoked = true;
        }
        if (shouldInvoke) invoke();
    }

    // Dispose() is called exactly once — from the worker's finally (Task.Run path) or from the
    // synchronous early-return path — always after InvokeCallbackOnce has set _callbackInvoked = true.
    public void Dispose() { Cts.Dispose(); }
}

internal static class _UniFFIAsync {
    internal const byte UNIFFI_RUST_FUTURE_POLL_READY = 0;
    // internal const byte UNIFFI_RUST_FUTURE_POLL_MAYBE_READY = 1;

    internal static ConcurrentHandleMap<TaskCompletionSource<byte>> _async_handle_map = new ConcurrentHandleMap<TaskCompletionSource<byte>>();
    public static ConcurrentHandleMap<UniffiForeignFutureHandle> _foreign_futures_map = new ConcurrentHandleMap<UniffiForeignFutureHandle>();

    // FFI type for Rust future continuations
    internal class UniffiRustFutureContinuationCallback
    {
        public static UniFfiFutureCallback callback = Callback;

        public static void Callback(ulong continuationHandle, byte pollResult)
        {
            if (_async_handle_map.Remove(continuationHandle, out TaskCompletionSource<byte>? task))
            {
                task.SetResult(pollResult);
            }
            // else: continuation already completed (e.g. waker called more than once), ignore
        }
    }

    public class UniffiForeignFutureDroppedCallbackImpl
    {
        public static _UniFFILib.UniffiForeignFutureDroppedCallback callback = Callback;

        public static void Callback(ulong handle)
        {
            if (_foreign_futures_map.Remove(handle, out UniffiForeignFutureHandle? futureHandle) && futureHandle is not null) {
                futureHandle.MarkDropped();
            }
        }
    }

    public delegate F CompleteFuncDelegate<F>(ulong handle, ref UniffiRustCallStatus status);

    public delegate void CompleteActionDelegate(ulong handle, ref UniffiRustCallStatus status);

    private static async Task PollFuture(ulong rustFuture, Action<ulong, IntPtr, ulong> pollFunc)
    {
        byte pollResult;
        do
        {
            var tcs = new TaskCompletionSource<byte>(TaskCreationOptions.RunContinuationsAsynchronously);
            IntPtr callback = Marshal.GetFunctionPointerForDelegate(UniffiRustFutureContinuationCallback.callback);
            ulong mapEntry = _async_handle_map.Insert(tcs);
            pollFunc(rustFuture, callback, mapEntry);
            pollResult = await tcs.Task;
        }
        while(pollResult != UNIFFI_RUST_FUTURE_POLL_READY);
    }

    public static async Task<T> UniffiRustCallAsync<T, F, E>(
        ulong rustFuture,
        Action<ulong, IntPtr, ulong> pollFunc,
        CompleteFuncDelegate<F> completeFunc,
        Action<ulong> freeFunc,
        Func<F, T> liftFunc,
        CallStatusErrorHandler<E> errorHandler
    ) where E : System.Exception
    {
        try {
            await PollFuture(rustFuture, pollFunc);
            var result = _UniffiHelpers.RustCallWithError(errorHandler, (ref UniffiRustCallStatus status) => completeFunc(rustFuture, ref status));
            return liftFunc(result);
        }
        finally
        {
            freeFunc(rustFuture);
        }
    }

    public static async Task UniffiRustCallAsync<E>(
        ulong rustFuture,
        Action<ulong, IntPtr, ulong> pollFunc,
        CompleteActionDelegate completeFunc,
        Action<ulong> freeFunc,
        CallStatusErrorHandler<E> errorHandler
    ) where E : System.Exception
    {
         try {
            await PollFuture(rustFuture, pollFunc);
            _UniffiHelpers.RustCallWithError(errorHandler, (ref UniffiRustCallStatus status) => completeFunc(rustFuture, ref status));

        }
        finally
        {
            freeFunc(rustFuture);
        }
    }
}
#pragma warning restore 8625
public static class LivekitTokenSourceMethods {
}
}
