#!/usr/bin/env python3
"""Post-process uniffi-bindgen-cs output so it compiles with C# 9 (Unity).

uniffi-bindgen-cs emits C# 10+ syntax, but Unity pins the compiler to C# 9.
This script rewrites the generated .cs files in place:

  * file-scoped namespace (`namespace Foo;`, C# 10) becomes a block-scoped
    namespace with the body indented by four spaces
  * `return [];` in sequence converters (collection expression, C# 12) becomes
    `return System.Array.Empty<T>();`
  * method groups stored in locals (`var readFn = FfiConverterX.INSTANCE.Read;`,
    inferred delegate type, C# 10) are removed and their calls inlined
  * when the bindings use records or `init` accessors (C# 9 syntax whose
    `System.Runtime.CompilerServices.IsExternalInit` marker type is missing
    from .NET Standard 2.1), an `IsExternalInit.cs` polyfill is written next to
    the bindings; it is removed again when no longer needed

Custom types that alias an array, nullable or tuple type (`using Foo = byte[];`,
C# 12) cannot be expressed in C# 9 and are reported as errors; change the
custom type mapping in uniffi.toml instead.

Two uniffi-bindgen-cs bugs in library-mode output that spans several crates
are worked around as well. Everything they insert is preceded by a comment
starting with `WORKAROUND(uniffi-bindgen-cs)` and points to the bug report
next to this script:

  * a custom type of another crate (e.g. `Bytes`) is only aliased in that
    crate's file, but C# `using` aliases are per file; the alias is repeated
    in every file that uses the type (UPSTREAM-external-custom-type-alias.md)
  * the converter of an object / callback interface of another crate is a
    plain alias of that crate's converter, whose Read/Write take that crate's
    BigEndianStream; a local forwarding converter that re-wraps the stream
    replaces the alias (UPSTREAM-external-object-converter-stream.md)

Usage:
    downgrade_uniffi_bindings.py [--no-polyfill] <file.cs | directory> [...]

Directories are scanned for *.cs files (non-recursive). The script is
idempotent: files that are already downgraded are left untouched.

--no-polyfill skips the `IsExternalInit.cs` polyfill (and removes one written
earlier) for assemblies that already define the marker type; the Unity SDK
ships it in Runtime/Scripts/Internal/IsExternalInit.cs.
"""

import re
import sys
from pathlib import Path

INDENT = "    "
MARKER = "//     Post-processed for C# 9 by Scripts~/uniffi/downgrade_uniffi_bindings.py"
POLYFILL_NAME = "IsExternalInit.cs"
POLYFILL = f"""// <auto-generated>
//     Written by Scripts~/uniffi/downgrade_uniffi_bindings.py. Do not edit.
//     The generated UniFFI bindings use C# 9 records / init accessors, which
//     require this marker type. .NET Standard 2.1 (Unity) does not ship it.
// </auto-generated>

#if !NET5_0_OR_GREATER
namespace System.Runtime.CompilerServices
{{
{INDENT}internal static class IsExternalInit {{ }}
}}
#endif
"""

FILE_SCOPED_NAMESPACE = re.compile(r"^\s*namespace\s+([A-Za-z_][\w.]*)\s*;\s*$")
# `public override T[] Read(BigEndianStream stream) {` in SequenceTemplate.cs
ARRAY_READ_SIGNATURE = re.compile(r"^\s*public\s+override\s+(?P<element>.+?)\s*\[\]\s+Read\s*\(\s*BigEndianStream\b")
EMPTY_COLLECTION_RETURN = re.compile(r"^(?P<indent>\s*)return\s*\[\s*\]\s*;\s*$")
# `using Alias = Target;` — C# 9 only allows (qualified, possibly generic) type names as Target
TYPE_ALIAS = re.compile(r"^\s*using\s+[A-Za-z_@]\w*\s*=\s*(?P<target>[^;]+);\s*$")
VALID_ALIAS_TARGET = re.compile(r"^[A-Za-z_@][\w.]*(\s*<.*>)?\s*$")
# `var readFn = FfiConverterX.INSTANCE.Read;` in SequenceTemplate.cs / MapTemplate.cs
METHOD_GROUP_LOCAL = re.compile(
    r"^\s*var\s+(?P<name>[A-Za-z_]\w*)\s*=\s*(?P<target>[A-Za-z_][\w.]*\.(?:Read|Write|AllocationSize))\s*;\s*$"
)
STRING_LITERAL = re.compile(r'\$?@?"(?:[^"\\]|\\.)*"')
RECORD_DECLARATION = re.compile(
    r"^\s*(?:(?:public|internal|private|protected|sealed|abstract|partial|static|new)\s+)*record\s+(?:struct\s+|class\s+)?[A-Za-z_@]"
)
INIT_ACCESSOR = re.compile(r"\binit\s*[;{]")

# ---------------------------------------------------------------------------
# WORKAROUNDS for uniffi-bindgen-cs (v0.11.0+v0.31.0) library-mode output that
# spans several crates. Both are generator bugs in its external-type templates;
# the bug reports for upstream (NordSecurity/uniffi-bindgen-cs) live next to
# this script:
#   UPSTREAM-external-custom-type-alias.md       -> import_external_custom_type_aliases()
#   UPSTREAM-external-object-converter-stream.md -> wrap_external_object_converters()
# Every line these insert into the bindings is preceded by a comment starting
# with WORKAROUND_TAG. Delete this whole section (and the two calls in
# process_file) once the bindgen release pinned in generate_uniffi_bindings.sh
# contains the fixes.
# ---------------------------------------------------------------------------
WORKAROUND_TAG = "WORKAROUND(uniffi-bindgen-cs)"
# `namespace Foo;` (file-scoped) or `namespace Foo` / `namespace Foo {` (block-scoped)
NAMESPACE_DECLARATION = re.compile(r"^\s*namespace\s+(?P<name>[A-Za-z_][\w.]*)\s*[;{]?\s*$")
ALIAS_DECLARATION = re.compile(r"^\s*using\s+(?P<name>[A-Za-z_@]\w*)\s*=\s*(?P<target>[^;]+);\s*$")
# `ns.FfiConverterTypeX.INSTANCE.Read(` inside the forwarding converters that
# ExternalTypeTemplate.cs generates for every record, enum, error or custom type
# used from another crate
EXTERNAL_CONVERTER_CALL = re.compile(
    r"(?P<namespace>[A-Za-z_][\w.]*)\.FfiConverterType(?P<name>\w+)\.INSTANCE\.Read\("
)
# `using FfiConverterTypeX = ns.FfiConverterTypeX;` from ExternalObjectTypeTemplate.cs
EXTERNAL_OBJECT_ALIAS = re.compile(
    r"^\s*using\s+(?P<converter>FfiConverterType\w+)\s*=\s*(?P<namespace>[A-Za-z_][\w.]*)\.(?P=converter)\s*;\s*$"
)
# `class FfiConverterTypeX : FfiConverter<CsType, FfiType>` as declared by the defining crate
CONVERTER_DECLARATION = re.compile(
    r"^\s*(?:\w+\s+)*class\s+(?P<converter>FfiConverterType\w+)\s*:\s*FfiConverter<(?P<cs_type>[^,<>]+),\s*(?P<ffi_type>[^<>]+)>"
)


def read_lines(path):
    """Returns (lines, bom, newline) of a generated file, without the trailing newline."""
    raw = path.read_bytes()
    bom = raw.startswith(b"\xef\xbb\xbf")
    text = raw[3:].decode("utf-8") if bom else raw.decode("utf-8")
    newline = "\r\n" if "\r\n" in text else "\n"
    lines = text.replace("\r\n", "\n").split("\n")
    if lines and lines[-1] == "":
        lines.pop()  # trailing newline is re-added on write
    return lines, bom, newline


class GeneratedFile:
    """What the cross-file workarounds need to know about one bindings file."""

    def __init__(self, path):
        self.path = path
        lines, _, _ = read_lines(path)
        namespaces = [m.group("name") for m in map(NAMESPACE_DECLARATION.match, lines) if m]
        self.namespace = namespaces[0] if namespaces else None
        self.aliases = {
            m.group("name"): m.group("target").strip() for m in map(ALIAS_DECLARATION.match, lines) if m
        }
        self.converters = {
            m.group("converter"): (m.group("cs_type").strip(), m.group("ffi_type").strip())
            for m in map(CONVERTER_DECLARATION.match, lines)
            if m
        }


def namespace_layout(lines):
    """Returns (body_start, body_end, indent) of the file's namespace: the line
    range that holds its members and the indentation members use."""
    for index, line in enumerate(lines):
        if NAMESPACE_DECLARATION.match(line):
            break
    else:
        raise ValueError("no namespace declaration found")

    if line.rstrip().endswith(";"):  # file-scoped: the body runs to the end of the file
        return index + 1, len(lines), ""

    body_start = index + 1 if line.rstrip().endswith("{") else index + 2
    for body_end in range(len(lines) - 1, index, -1):
        if lines[body_end].strip() == "}":
            return body_start, body_end, INDENT
    raise ValueError("block-scoped namespace without closing brace")


def import_external_custom_type_aliases(lines, siblings):
    """WORKAROUND: repeat the `using Name = Target;` alias of a custom type that
    another crate defines in the file that uses it. uniffi-bindgen-cs emits the
    alias only in the defining crate's file, but C# `using` aliases are per file
    (UPSTREAM-external-custom-type-alias.md). Returns (lines, changed)."""
    by_namespace = {sibling.namespace: sibling for sibling in siblings if sibling.namespace}
    declared = {m.group("name") for m in map(ALIAS_DECLARATION.match, lines) if m}
    missing = {}
    for match in EXTERNAL_CONVERTER_CALL.finditer("\n".join(lines)):
        namespace, name = match.group("namespace"), match.group("name")
        sibling = by_namespace.get(namespace)
        if sibling is None or name in declared:
            continue
        target = sibling.aliases.get(name)
        if target is not None:  # only custom types are aliases; records and enums resolve via `using ns;`
            missing[name] = (namespace, target)
    if not missing:
        return lines, False

    body_start, _, indent = namespace_layout(lines)
    inserted = []
    for name, (namespace, target) in sorted(missing.items()):
        inserted += [
            f"{indent}// {WORKAROUND_TAG}: `{name}` is a custom type of {namespace}, the only file uniffi-bindgen-cs",
            f"{indent}// aliases it in. See Scripts~/uniffi/UPSTREAM-external-custom-type-alias.md",
            f"{indent}using {name} = {target};",
        ]
    return lines[:body_start] + inserted + lines[body_start:], True


def external_object_converter(converter, namespace, cs_type, ffi_type):
    """A local converter that forwards to `namespace.converter` and re-wraps the
    stream, like ExternalTypeTemplate.cs already does for records and enums."""
    remote = f"{namespace}.{converter}.INSTANCE"
    if "." not in cs_type:
        cs_type = f"{namespace}.{cs_type}"
    return [
        f"// {WORKAROUND_TAG}: `{converter}` belongs to {namespace}. uniffi-bindgen-cs aliases that",
        "// crate's converter directly, whose Read/Write take that crate's BigEndianStream instead of",
        "// this file's. This forwarding converter re-wraps the stream the way the generator already",
        "// does for external records and enums. See Scripts~/uniffi/UPSTREAM-external-object-converter-stream.md",
        f"class {converter} : FfiConverter<{cs_type}, {ffi_type}>",
        "{",
        f"{INDENT}public static {converter} INSTANCE = new {converter}();",
        "",
        f"{INDENT}public override {cs_type} Lift({ffi_type} value)",
        f"{INDENT}{{",
        f"{INDENT}{INDENT}return {remote}.Lift(value);",
        f"{INDENT}}}",
        "",
        f"{INDENT}public override {ffi_type} Lower({cs_type} value)",
        f"{INDENT}{{",
        f"{INDENT}{INDENT}return {remote}.Lower(value);",
        f"{INDENT}}}",
        "",
        f"{INDENT}public override {cs_type} Read(BigEndianStream stream)",
        f"{INDENT}{{",
        f"{INDENT}{INDENT}return {remote}.Read(new {namespace}.BigEndianStream(stream.InnerStream));",
        f"{INDENT}}}",
        "",
        f"{INDENT}public override int AllocationSize({cs_type} value)",
        f"{INDENT}{{",
        f"{INDENT}{INDENT}return {remote}.AllocationSize(value);",
        f"{INDENT}}}",
        "",
        f"{INDENT}public override void Write({cs_type} value, BigEndianStream stream)",
        f"{INDENT}{{",
        f"{INDENT}{INDENT}{remote}.Write(value, new {namespace}.BigEndianStream(stream.InnerStream));",
        f"{INDENT}}}",
        "}",
    ]


def wrap_external_object_converters(lines, siblings):
    """WORKAROUND: replace `using FfiConverterTypeX = ns.FfiConverterTypeX;` for
    an object or callback interface of another crate with a local forwarding
    converter (UPSTREAM-external-object-converter-stream.md). Returns (lines, changed)."""
    by_namespace = {sibling.namespace: sibling for sibling in siblings if sibling.namespace}
    kept, converters = [], []
    for number, line in enumerate(lines, start=1):
        alias = EXTERNAL_OBJECT_ALIAS.match(line)
        if not alias:
            kept.append(line)
            continue
        converter, namespace = alias.group("converter"), alias.group("namespace")
        sibling = by_namespace.get(namespace)
        declaration = sibling.converters.get(converter) if sibling else None
        if declaration is None:
            raise ValueError(
                f"line {number}: `{line.strip()}` refers to a converter of {namespace}, but no generated file "
                f"in this directory declares `class {converter} : FfiConverter<...>`; run this script on the "
                "directory that holds all bindings of the library"
            )
        converters.append(external_object_converter(converter, namespace, *declaration))
    if not converters:
        return lines, False

    _, body_end, indent = namespace_layout(kept)
    body = []
    for converter in converters:
        body += [""] + [indent + line if line else "" for line in converter]
    return kept[:body_end] + body + kept[body_end:], True


def block_scope_namespace(lines):
    """Wrap everything after a file-scoped namespace declaration into a
    block-scoped namespace. Returns (lines, changed)."""
    matches = [i for i, line in enumerate(lines) if FILE_SCOPED_NAMESPACE.match(line)]
    if not matches:
        return lines, False
    if len(matches) > 1:
        raise ValueError(f"expected a single file-scoped namespace, found {len(matches)}")

    index = matches[0]
    name = FILE_SCOPED_NAMESPACE.match(lines[index]).group(1)

    body = []
    for line in lines[index + 1 :]:
        stripped = line.strip()
        if not stripped:
            body.append("")
        elif stripped.startswith("#"):
            # Keep preprocessor directives at column 0, as CSharpier does.
            body.append(line)
        else:
            body.append(INDENT + line)

    # Drop blank lines directly inside the braces.
    while body and not body[0]:
        body.pop(0)
    while body and not body[-1]:
        body.pop()

    return lines[:index] + [f"namespace {name}", "{"] + body + ["}"], True


def replace_empty_collection_returns(lines):
    """`return [];` -> `return System.Array.Empty<T>();`, taking T from the
    enclosing `T[] Read(BigEndianStream)` signature. Returns (lines, changed)."""
    result = []
    element = None
    changed = False
    for number, line in enumerate(lines, start=1):
        signature = ARRAY_READ_SIGNATURE.match(line)
        if signature:
            element = signature.group("element").strip()
        elif "override" in line and "(" in line:
            element = None  # a different method started

        empty_return = EMPTY_COLLECTION_RETURN.match(line)
        if empty_return:
            if element is None:
                raise ValueError(f"line {number}: `return [];` outside of a sequence Read() method")
            line = f"{empty_return.group('indent')}return System.Array.Empty<{element}>();"
            changed = True
        result.append(line)
    return result, changed


def inline_method_groups(lines):
    """Drop `var fn = Converter.INSTANCE.Method;` locals and call the method
    directly wherever `fn(...)` is used in the enclosing block. Returns
    (lines, changed)."""
    lines = list(lines)
    result = []
    changed = False
    for i, line in enumerate(lines):
        local = METHOD_GROUP_LOCAL.match(line)
        if not local:
            result.append(line)
            continue

        name, target = local.group("name"), local.group("target")
        call = re.compile(rf"\b{re.escape(name)}\s*\(")
        bare = re.compile(rf"\b{re.escape(name)}\b")
        depth = 0
        for j in range(i + 1, len(lines)):
            without_strings = STRING_LITERAL.sub('""', lines[j])
            depth += without_strings.count("{") - without_strings.count("}")
            if depth < 0:
                break  # enclosing block closed
            lines[j] = call.sub(f"{target}(", lines[j])
            if bare.search(lines[j]):
                raise ValueError(
                    f"line {j + 1}: `{name}` is used as a delegate value; cannot inline method group `{target}`"
                )
        changed = True  # declaration line is dropped
    return result, changed


def check_type_aliases(lines):
    for number, line in enumerate(lines, start=1):
        alias = TYPE_ALIAS.match(line)
        if alias and not VALID_ALIAS_TARGET.match(alias.group("target")):
            raise ValueError(
                f"line {number}: `{line.strip()}` needs C# 12 (alias any type); "
                "map this custom type to a named type in uniffi.toml"
            )


def add_marker(lines):
    """Record the post-processing in the <auto-generated> header, if present."""
    if MARKER in lines:
        return lines
    for i, line in enumerate(lines[:10]):
        if line.strip() == "// </auto-generated>":
            return lines[:i] + [MARKER] + lines[i:]
    return lines


def needs_is_external_init(lines):
    return any(RECORD_DECLARATION.match(line) or INIT_ACCESSOR.search(line) for line in lines)


def process_file(path, siblings=()):
    """Returns (changed, needs_polyfill). `siblings` are the other generated
    files of the same library (GeneratedFile), needed by the uniffi-bindgen-cs
    workarounds."""
    lines, bom, newline = read_lines(path)

    # uniffi-bindgen-cs workarounds first; what they insert is treated like
    # generated code by the C# 9 steps below.
    lines, aliases_added = import_external_custom_type_aliases(lines, siblings)
    lines, converters_wrapped = wrap_external_object_converters(lines, siblings)

    check_type_aliases(lines)
    lines, namespace_changed = block_scope_namespace(lines)
    lines, returns_changed = replace_empty_collection_returns(lines)
    lines, method_groups_changed = inline_method_groups(lines)
    changed = aliases_added or converters_wrapped or namespace_changed or returns_changed or method_groups_changed

    if changed:
        lines = add_marker(lines)
        out = newline.join(lines) + newline
        path.write_bytes((b"\xef\xbb\xbf" if bom else b"") + out.encode("utf-8"))

    return changed, needs_is_external_init(lines)


def sync_polyfill(directory, needed):
    """Create or remove IsExternalInit.cs (and its Unity .meta) in `directory`."""
    polyfill = directory / POLYFILL_NAME
    if needed:
        if not polyfill.exists() or polyfill.read_text(encoding="utf-8") != POLYFILL:
            polyfill.write_text(POLYFILL, encoding="utf-8")
            print(f"  wrote      {polyfill}")
    elif polyfill.exists() and "downgrade_uniffi_bindings.py" in polyfill.read_text(encoding="utf-8"):
        polyfill.unlink()
        print(f"  removed    {polyfill}")
        meta = polyfill.with_name(POLYFILL_NAME + ".meta")
        if meta.exists():
            meta.unlink()
            print(f"  removed    {meta}")


def main(argv):
    no_polyfill = "--no-polyfill" in argv[1:]
    targets = [arg for arg in argv[1:] if arg != "--no-polyfill"]
    if not targets or any(arg.startswith("--") for arg in targets):
        print(__doc__.strip())
        return 2

    status = 0
    for arg in targets:
        target = Path(arg)
        if target.is_dir():
            directory = target
            files = sorted(p for p in target.glob("*.cs") if p.name != POLYFILL_NAME)
        elif target.is_file():
            directory = target.parent
            files = [target]
        else:
            print(f"error: {target} does not exist", file=sys.stderr)
            status = 1
            continue

        # All bindings files of the library, for the cross-file workarounds.
        generated = [GeneratedFile(p) for p in sorted(directory.glob("*.cs")) if p.name != POLYFILL_NAME]

        polyfill_needed = False
        for path in files:
            siblings = [g for g in generated if g.path.resolve() != path.resolve()]
            try:
                changed, needs_polyfill = process_file(path, siblings)
            except (ValueError, UnicodeDecodeError) as exc:
                print(f"error: {path}: {exc}", file=sys.stderr)
                status = 1
                continue
            polyfill_needed |= needs_polyfill
            print(f"  {'downgraded' if changed else 'unchanged '} {path}")

        sync_polyfill(directory, polyfill_needed and not no_polyfill)

    return status


if __name__ == "__main__":
    sys.exit(main(sys.argv))
