// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: participant.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace LiveKit.Proto {

  /// <summary>Holder for reflection information generated from participant.proto</summary>
  public static partial class ParticipantReflection {

    #region Descriptor
    /// <summary>File descriptor for participant.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ParticipantReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFwYXJ0aWNpcGFudC5wcm90bxINbGl2ZWtpdC5wcm90bxoMaGFuZGxlLnBy",
            "b3RvGgt0cmFjay5wcm90byKnAwoPUGFydGljaXBhbnRJbmZvEgsKA3NpZBgB",
            "IAIoCRIMCgRuYW1lGAIgAigJEhAKCGlkZW50aXR5GAMgAigJEhAKCG1ldGFk",
            "YXRhGAQgAigJEkIKCmF0dHJpYnV0ZXMYBSADKAsyLi5saXZla2l0LnByb3Rv",
            "LlBhcnRpY2lwYW50SW5mby5BdHRyaWJ1dGVzRW50cnkSLAoEa2luZBgGIAIo",
            "DjIeLmxpdmVraXQucHJvdG8uUGFydGljaXBhbnRLaW5kEjoKEWRpc2Nvbm5l",
            "Y3RfcmVhc29uGAcgAigOMh8ubGl2ZWtpdC5wcm90by5EaXNjb25uZWN0UmVh",
            "c29uEjoKDGtpbmRfZGV0YWlscxgIIAMoDjIkLmxpdmVraXQucHJvdG8uUGFy",
            "dGljaXBhbnRLaW5kRGV0YWlsEjgKCnBlcm1pc3Npb24YCSABKAsyJC5saXZl",
            "a2l0LnByb3RvLlBhcnRpY2lwYW50UGVybWlzc2lvbhoxCg9BdHRyaWJ1dGVz",
            "RW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASJvChBPd25l",
            "ZFBhcnRpY2lwYW50Ei0KBmhhbmRsZRgBIAIoCzIdLmxpdmVraXQucHJvdG8u",
            "RmZpT3duZWRIYW5kbGUSLAoEaW5mbxgCIAIoCzIeLmxpdmVraXQucHJvdG8u",
            "UGFydGljaXBhbnRJbmZvIoQCChVQYXJ0aWNpcGFudFBlcm1pc3Npb24SFQoN",
            "Y2FuX3N1YnNjcmliZRgBIAIoCBITCgtjYW5fcHVibGlzaBgCIAIoCBIYChBj",
            "YW5fcHVibGlzaF9kYXRhGAMgAigIEjcKE2Nhbl9wdWJsaXNoX3NvdXJjZXMY",
            "CSADKA4yGi5saXZla2l0LnByb3RvLlRyYWNrU291cmNlEg4KBmhpZGRlbhgH",
            "IAIoCBIbChNjYW5fdXBkYXRlX21ldGFkYXRhGAogAigIEh0KFWNhbl9zdWJz",
            "Y3JpYmVfbWV0cmljcxgMIAIoCBIgChhjYW5fbWFuYWdlX2FnZW50X3Nlc3Np",
            "b24YDSACKAgq3gEKD1BhcnRpY2lwYW50S2luZBIdChlQQVJUSUNJUEFOVF9L",
            "SU5EX1NUQU5EQVJEEAASHAoYUEFSVElDSVBBTlRfS0lORF9JTkdSRVNTEAES",
            "GwoXUEFSVElDSVBBTlRfS0lORF9FR1JFU1MQAhIYChRQQVJUSUNJUEFOVF9L",
            "SU5EX1NJUBADEhoKFlBBUlRJQ0lQQU5UX0tJTkRfQUdFTlQQBBIeChpQQVJU",
            "SUNJUEFOVF9LSU5EX0NPTk5FQ1RPUhAFEhsKF1BBUlRJQ0lQQU5UX0tJTkRf",
            "QlJJREdFEAYq7gEKFVBhcnRpY2lwYW50S2luZERldGFpbBInCiNQQVJUSUNJ",
            "UEFOVF9LSU5EX0RFVEFJTF9DTE9VRF9BR0VOVBAAEiUKIVBBUlRJQ0lQQU5U",
            "X0tJTkRfREVUQUlMX0ZPUldBUkRFRBABEi4KKlBBUlRJQ0lQQU5UX0tJTkRf",
            "REVUQUlMX0NPTk5FQ1RPUl9XSEFUU0FQUBACEiwKKFBBUlRJQ0lQQU5UX0tJ",
            "TkRfREVUQUlMX0NPTk5FQ1RPUl9UV0lMSU8QAxInCiNQQVJUSUNJUEFOVF9L",
            "SU5EX0RFVEFJTF9CUklER0VfUlRTUBAEKtcCChBEaXNjb25uZWN0UmVhc29u",
            "EhIKDlVOS05PV05fUkVBU09OEAASFAoQQ0xJRU5UX0lOSVRJQVRFRBABEhYK",
            "EkRVUExJQ0FURV9JREVOVElUWRACEhMKD1NFUlZFUl9TSFVURE9XThADEhcK",
            "E1BBUlRJQ0lQQU5UX1JFTU9WRUQQBBIQCgxST09NX0RFTEVURUQQBRISCg5T",
            "VEFURV9NSVNNQVRDSBAGEhAKDEpPSU5fRkFJTFVSRRAHEg0KCU1JR1JBVElP",
            "ThAIEhAKDFNJR05BTF9DTE9TRRAJEg8KC1JPT01fQ0xPU0VEEAoSFAoQVVNF",
            "Ul9VTkFWQUlMQUJMRRALEhEKDVVTRVJfUkVKRUNURUQQDBIVChFTSVBfVFJV",
            "TktfRkFJTFVSRRANEhYKEkNPTk5FQ1RJT05fVElNRU9VVBAOEhEKDU1FRElB",
            "X0ZBSUxVUkUQD0IQqgINTGl2ZUtpdC5Qcm90bw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::LiveKit.Proto.HandleReflection.Descriptor, global::LiveKit.Proto.TrackReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::LiveKit.Proto.ParticipantKind), typeof(global::LiveKit.Proto.ParticipantKindDetail), typeof(global::LiveKit.Proto.DisconnectReason), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::LiveKit.Proto.ParticipantInfo), global::LiveKit.Proto.ParticipantInfo.Parser, new[]{ "Sid", "Name", "Identity", "Metadata", "Attributes", "Kind", "DisconnectReason", "KindDetails", "Permission" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::LiveKit.Proto.OwnedParticipant), global::LiveKit.Proto.OwnedParticipant.Parser, new[]{ "Handle", "Info" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::LiveKit.Proto.ParticipantPermission), global::LiveKit.Proto.ParticipantPermission.Parser, new[]{ "CanSubscribe", "CanPublish", "CanPublishData", "CanPublishSources", "Hidden", "CanUpdateMetadata", "CanSubscribeMetrics", "CanManageAgentSession" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ParticipantKind {
    [pbr::OriginalName("PARTICIPANT_KIND_STANDARD")] Standard = 0,
    [pbr::OriginalName("PARTICIPANT_KIND_INGRESS")] Ingress = 1,
    [pbr::OriginalName("PARTICIPANT_KIND_EGRESS")] Egress = 2,
    [pbr::OriginalName("PARTICIPANT_KIND_SIP")] Sip = 3,
    [pbr::OriginalName("PARTICIPANT_KIND_AGENT")] Agent = 4,
    [pbr::OriginalName("PARTICIPANT_KIND_CONNECTOR")] Connector = 5,
    [pbr::OriginalName("PARTICIPANT_KIND_BRIDGE")] Bridge = 6,
  }

  public enum ParticipantKindDetail {
    [pbr::OriginalName("PARTICIPANT_KIND_DETAIL_CLOUD_AGENT")] CloudAgent = 0,
    [pbr::OriginalName("PARTICIPANT_KIND_DETAIL_FORWARDED")] Forwarded = 1,
    [pbr::OriginalName("PARTICIPANT_KIND_DETAIL_CONNECTOR_WHATSAPP")] ConnectorWhatsapp = 2,
    [pbr::OriginalName("PARTICIPANT_KIND_DETAIL_CONNECTOR_TWILIO")] ConnectorTwilio = 3,
    [pbr::OriginalName("PARTICIPANT_KIND_DETAIL_BRIDGE_RTSP")] BridgeRtsp = 4,
  }

  public enum DisconnectReason {
    [pbr::OriginalName("UNKNOWN_REASON")] UnknownReason = 0,
    /// <summary>
    /// the client initiated the disconnect
    /// </summary>
    [pbr::OriginalName("CLIENT_INITIATED")] ClientInitiated = 1,
    /// <summary>
    /// another participant with the same identity has joined the room
    /// </summary>
    [pbr::OriginalName("DUPLICATE_IDENTITY")] DuplicateIdentity = 2,
    /// <summary>
    /// the server instance is shutting down
    /// </summary>
    [pbr::OriginalName("SERVER_SHUTDOWN")] ServerShutdown = 3,
    /// <summary>
    /// RoomService.RemoveParticipant was called
    /// </summary>
    [pbr::OriginalName("PARTICIPANT_REMOVED")] ParticipantRemoved = 4,
    /// <summary>
    /// RoomService.DeleteRoom was called
    /// </summary>
    [pbr::OriginalName("ROOM_DELETED")] RoomDeleted = 5,
    /// <summary>
    /// the client is attempting to resume a session, but server is not aware of it
    /// </summary>
    [pbr::OriginalName("STATE_MISMATCH")] StateMismatch = 6,
    /// <summary>
    /// client was unable to connect fully
    /// </summary>
    [pbr::OriginalName("JOIN_FAILURE")] JoinFailure = 7,
    /// <summary>
    /// Cloud-only, the server requested Participant to migrate the connection elsewhere
    /// </summary>
    [pbr::OriginalName("MIGRATION")] Migration = 8,
    /// <summary>
    /// the signal websocket was closed unexpectedly
    /// </summary>
    [pbr::OriginalName("SIGNAL_CLOSE")] SignalClose = 9,
    /// <summary>
    /// the room was closed, due to all Standard and Ingress participants having left
    /// </summary>
    [pbr::OriginalName("ROOM_CLOSED")] RoomClosed = 10,
    /// <summary>
    /// SIP callee did not respond in time
    /// </summary>
    [pbr::OriginalName("USER_UNAVAILABLE")] UserUnavailable = 11,
    /// <summary>
    /// SIP callee rejected the call (busy)
    /// </summary>
    [pbr::OriginalName("USER_REJECTED")] UserRejected = 12,
    /// <summary>
    /// SIP protocol failure or unexpected response
    /// </summary>
    [pbr::OriginalName("SIP_TRUNK_FAILURE")] SipTrunkFailure = 13,
    [pbr::OriginalName("CONNECTION_TIMEOUT")] ConnectionTimeout = 14,
    [pbr::OriginalName("MEDIA_FAILURE")] MediaFailure = 15,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ParticipantInfo : pb::IMessage<ParticipantInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ParticipantInfo> _parser = new pb::MessageParser<ParticipantInfo>(() => new ParticipantInfo());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ParticipantInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LiveKit.Proto.ParticipantReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ParticipantInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ParticipantInfo(ParticipantInfo other) : this() {
      _hasBits0 = other._hasBits0;
      sid_ = other.sid_;
      name_ = other.name_;
      identity_ = other.identity_;
      metadata_ = other.metadata_;
      attributes_ = other.attributes_.Clone();
      kind_ = other.kind_;
      disconnectReason_ = other.disconnectReason_;
      kindDetails_ = other.kindDetails_.Clone();
      permission_ = other.permission_ != null ? other.permission_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ParticipantInfo Clone() {
      return new ParticipantInfo(this);
    }

    /// <summary>Field number for the "sid" field.</summary>
    public const int SidFieldNumber = 1;
    private readonly static string SidDefaultValue = "";

    private string sid_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Sid {
      get { return sid_ ?? SidDefaultValue; }
      set {
        sid_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "sid" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasSid {
      get { return sid_ != null; }
    }
    /// <summary>Clears the value of the "sid" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearSid() {
      sid_ = null;
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private readonly static string NameDefaultValue = "";

    private string name_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_ ?? NameDefaultValue; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "name" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasName {
      get { return name_ != null; }
    }
    /// <summary>Clears the value of the "name" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearName() {
      name_ = null;
    }

    /// <summary>Field number for the "identity" field.</summary>
    public const int IdentityFieldNumber = 3;
    private readonly static string IdentityDefaultValue = "";

    private string identity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Identity {
      get { return identity_ ?? IdentityDefaultValue; }
      set {
        identity_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "identity" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasIdentity {
      get { return identity_ != null; }
    }
    /// <summary>Clears the value of the "identity" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearIdentity() {
      identity_ = null;
    }

    /// <summary>Field number for the "metadata" field.</summary>
    public const int MetadataFieldNumber = 4;
    private readonly static string MetadataDefaultValue = "";

    private string metadata_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Metadata {
      get { return metadata_ ?? MetadataDefaultValue; }
      set {
        metadata_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "metadata" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasMetadata {
      get { return metadata_ != null; }
    }
    /// <summary>Clears the value of the "metadata" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearMetadata() {
      metadata_ = null;
    }

    /// <summary>Field number for the "attributes" field.</summary>
    public const int AttributesFieldNumber = 5;
    private static readonly pbc::MapField<string, string>.Codec _map_attributes_codec
        = new pbc::MapField<string, string>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForString(18, ""), 42);
    private readonly pbc::MapField<string, string> attributes_ = new pbc::MapField<string, string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, string> Attributes {
      get { return attributes_; }
    }

    /// <summary>Field number for the "kind" field.</summary>
    public const int KindFieldNumber = 6;
    private readonly static global::LiveKit.Proto.ParticipantKind KindDefaultValue = global::LiveKit.Proto.ParticipantKind.Standard;

    private global::LiveKit.Proto.ParticipantKind kind_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LiveKit.Proto.ParticipantKind Kind {
      get { if ((_hasBits0 & 1) != 0) { return kind_; } else { return KindDefaultValue; } }
      set {
        _hasBits0 |= 1;
        kind_ = value;
      }
    }
    /// <summary>Gets whether the "kind" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasKind {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "kind" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearKind() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "disconnect_reason" field.</summary>
    public const int DisconnectReasonFieldNumber = 7;
    private readonly static global::LiveKit.Proto.DisconnectReason DisconnectReasonDefaultValue = global::LiveKit.Proto.DisconnectReason.UnknownReason;

    private global::LiveKit.Proto.DisconnectReason disconnectReason_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LiveKit.Proto.DisconnectReason DisconnectReason {
      get { if ((_hasBits0 & 2) != 0) { return disconnectReason_; } else { return DisconnectReasonDefaultValue; } }
      set {
        _hasBits0 |= 2;
        disconnectReason_ = value;
      }
    }
    /// <summary>Gets whether the "disconnect_reason" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasDisconnectReason {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "disconnect_reason" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearDisconnectReason() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "kind_details" field.</summary>
    public const int KindDetailsFieldNumber = 8;
    private static readonly pb::FieldCodec<global::LiveKit.Proto.ParticipantKindDetail> _repeated_kindDetails_codec
        = pb::FieldCodec.ForEnum(64, x => (int) x, x => (global::LiveKit.Proto.ParticipantKindDetail) x);
    private readonly pbc::RepeatedField<global::LiveKit.Proto.ParticipantKindDetail> kindDetails_ = new pbc::RepeatedField<global::LiveKit.Proto.ParticipantKindDetail>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::LiveKit.Proto.ParticipantKindDetail> KindDetails {
      get { return kindDetails_; }
    }

    /// <summary>Field number for the "permission" field.</summary>
    public const int PermissionFieldNumber = 9;
    private global::LiveKit.Proto.ParticipantPermission permission_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LiveKit.Proto.ParticipantPermission Permission {
      get { return permission_; }
      set {
        permission_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ParticipantInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ParticipantInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Sid != other.Sid) return false;
      if (Name != other.Name) return false;
      if (Identity != other.Identity) return false;
      if (Metadata != other.Metadata) return false;
      if (!Attributes.Equals(other.Attributes)) return false;
      if (Kind != other.Kind) return false;
      if (DisconnectReason != other.DisconnectReason) return false;
      if(!kindDetails_.Equals(other.kindDetails_)) return false;
      if (!object.Equals(Permission, other.Permission)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasSid) hash ^= Sid.GetHashCode();
      if (HasName) hash ^= Name.GetHashCode();
      if (HasIdentity) hash ^= Identity.GetHashCode();
      if (HasMetadata) hash ^= Metadata.GetHashCode();
      hash ^= Attributes.GetHashCode();
      if (HasKind) hash ^= Kind.GetHashCode();
      if (HasDisconnectReason) hash ^= DisconnectReason.GetHashCode();
      hash ^= kindDetails_.GetHashCode();
      if (permission_ != null) hash ^= Permission.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasSid) {
        output.WriteRawTag(10);
        output.WriteString(Sid);
      }
      if (HasName) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (HasIdentity) {
        output.WriteRawTag(26);
        output.WriteString(Identity);
      }
      if (HasMetadata) {
        output.WriteRawTag(34);
        output.WriteString(Metadata);
      }
      attributes_.WriteTo(output, _map_attributes_codec);
      if (HasKind) {
        output.WriteRawTag(48);
        output.WriteEnum((int) Kind);
      }
      if (HasDisconnectReason) {
        output.WriteRawTag(56);
        output.WriteEnum((int) DisconnectReason);
      }
      kindDetails_.WriteTo(output, _repeated_kindDetails_codec);
      if (permission_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(Permission);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasSid) {
        output.WriteRawTag(10);
        output.WriteString(Sid);
      }
      if (HasName) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (HasIdentity) {
        output.WriteRawTag(26);
        output.WriteString(Identity);
      }
      if (HasMetadata) {
        output.WriteRawTag(34);
        output.WriteString(Metadata);
      }
      attributes_.WriteTo(ref output, _map_attributes_codec);
      if (HasKind) {
        output.WriteRawTag(48);
        output.WriteEnum((int) Kind);
      }
      if (HasDisconnectReason) {
        output.WriteRawTag(56);
        output.WriteEnum((int) DisconnectReason);
      }
      kindDetails_.WriteTo(ref output, _repeated_kindDetails_codec);
      if (permission_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(Permission);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasSid) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Sid);
      }
      if (HasName) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (HasIdentity) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Identity);
      }
      if (HasMetadata) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Metadata);
      }
      size += attributes_.CalculateSize(_map_attributes_codec);
      if (HasKind) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Kind);
      }
      if (HasDisconnectReason) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) DisconnectReason);
      }
      size += kindDetails_.CalculateSize(_repeated_kindDetails_codec);
      if (permission_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Permission);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ParticipantInfo other) {
      if (other == null) {
        return;
      }
      if (other.HasSid) {
        Sid = other.Sid;
      }
      if (other.HasName) {
        Name = other.Name;
      }
      if (other.HasIdentity) {
        Identity = other.Identity;
      }
      if (other.HasMetadata) {
        Metadata = other.Metadata;
      }
      attributes_.MergeFrom(other.attributes_);
      if (other.HasKind) {
        Kind = other.Kind;
      }
      if (other.HasDisconnectReason) {
        DisconnectReason = other.DisconnectReason;
      }
      kindDetails_.Add(other.kindDetails_);
      if (other.permission_ != null) {
        if (permission_ == null) {
          Permission = new global::LiveKit.Proto.ParticipantPermission();
        }
        Permission.MergeFrom(other.Permission);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Sid = input.ReadString();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            Identity = input.ReadString();
            break;
          }
          case 34: {
            Metadata = input.ReadString();
            break;
          }
          case 42: {
            attributes_.AddEntriesFrom(input, _map_attributes_codec);
            break;
          }
          case 48: {
            Kind = (global::LiveKit.Proto.ParticipantKind) input.ReadEnum();
            break;
          }
          case 56: {
            DisconnectReason = (global::LiveKit.Proto.DisconnectReason) input.ReadEnum();
            break;
          }
          case 66:
          case 64: {
            kindDetails_.AddEntriesFrom(input, _repeated_kindDetails_codec);
            break;
          }
          case 74: {
            if (permission_ == null) {
              Permission = new global::LiveKit.Proto.ParticipantPermission();
            }
            input.ReadMessage(Permission);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Sid = input.ReadString();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            Identity = input.ReadString();
            break;
          }
          case 34: {
            Metadata = input.ReadString();
            break;
          }
          case 42: {
            attributes_.AddEntriesFrom(ref input, _map_attributes_codec);
            break;
          }
          case 48: {
            Kind = (global::LiveKit.Proto.ParticipantKind) input.ReadEnum();
            break;
          }
          case 56: {
            DisconnectReason = (global::LiveKit.Proto.DisconnectReason) input.ReadEnum();
            break;
          }
          case 66:
          case 64: {
            kindDetails_.AddEntriesFrom(ref input, _repeated_kindDetails_codec);
            break;
          }
          case 74: {
            if (permission_ == null) {
              Permission = new global::LiveKit.Proto.ParticipantPermission();
            }
            input.ReadMessage(Permission);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OwnedParticipant : pb::IMessage<OwnedParticipant>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OwnedParticipant> _parser = new pb::MessageParser<OwnedParticipant>(() => new OwnedParticipant());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OwnedParticipant> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LiveKit.Proto.ParticipantReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OwnedParticipant() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OwnedParticipant(OwnedParticipant other) : this() {
      handle_ = other.handle_ != null ? other.handle_.Clone() : null;
      info_ = other.info_ != null ? other.info_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OwnedParticipant Clone() {
      return new OwnedParticipant(this);
    }

    /// <summary>Field number for the "handle" field.</summary>
    public const int HandleFieldNumber = 1;
    private global::LiveKit.Proto.FfiOwnedHandle handle_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LiveKit.Proto.FfiOwnedHandle Handle {
      get { return handle_; }
      set {
        handle_ = value;
      }
    }

    /// <summary>Field number for the "info" field.</summary>
    public const int InfoFieldNumber = 2;
    private global::LiveKit.Proto.ParticipantInfo info_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::LiveKit.Proto.ParticipantInfo Info {
      get { return info_; }
      set {
        info_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OwnedParticipant);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OwnedParticipant other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Handle, other.Handle)) return false;
      if (!object.Equals(Info, other.Info)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (handle_ != null) hash ^= Handle.GetHashCode();
      if (info_ != null) hash ^= Info.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (handle_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Handle);
      }
      if (info_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Info);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (handle_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Handle);
      }
      if (info_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Info);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (handle_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Handle);
      }
      if (info_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Info);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OwnedParticipant other) {
      if (other == null) {
        return;
      }
      if (other.handle_ != null) {
        if (handle_ == null) {
          Handle = new global::LiveKit.Proto.FfiOwnedHandle();
        }
        Handle.MergeFrom(other.Handle);
      }
      if (other.info_ != null) {
        if (info_ == null) {
          Info = new global::LiveKit.Proto.ParticipantInfo();
        }
        Info.MergeFrom(other.Info);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (handle_ == null) {
              Handle = new global::LiveKit.Proto.FfiOwnedHandle();
            }
            input.ReadMessage(Handle);
            break;
          }
          case 18: {
            if (info_ == null) {
              Info = new global::LiveKit.Proto.ParticipantInfo();
            }
            input.ReadMessage(Info);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (handle_ == null) {
              Handle = new global::LiveKit.Proto.FfiOwnedHandle();
            }
            input.ReadMessage(Handle);
            break;
          }
          case 18: {
            if (info_ == null) {
              Info = new global::LiveKit.Proto.ParticipantInfo();
            }
            input.ReadMessage(Info);
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  /// copied from livekit-protocol/protocol/protobufs/livekit_models.proto and removed deprecated fields
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ParticipantPermission : pb::IMessage<ParticipantPermission>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ParticipantPermission> _parser = new pb::MessageParser<ParticipantPermission>(() => new ParticipantPermission());
    private pb::UnknownFieldSet _unknownFields;
    private int _hasBits0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ParticipantPermission> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::LiveKit.Proto.ParticipantReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ParticipantPermission() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ParticipantPermission(ParticipantPermission other) : this() {
      _hasBits0 = other._hasBits0;
      canSubscribe_ = other.canSubscribe_;
      canPublish_ = other.canPublish_;
      canPublishData_ = other.canPublishData_;
      canPublishSources_ = other.canPublishSources_.Clone();
      hidden_ = other.hidden_;
      canUpdateMetadata_ = other.canUpdateMetadata_;
      canSubscribeMetrics_ = other.canSubscribeMetrics_;
      canManageAgentSession_ = other.canManageAgentSession_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ParticipantPermission Clone() {
      return new ParticipantPermission(this);
    }

    /// <summary>Field number for the "can_subscribe" field.</summary>
    public const int CanSubscribeFieldNumber = 1;
    private readonly static bool CanSubscribeDefaultValue = false;

    private bool canSubscribe_;
    /// <summary>
    /// allow participant to subscribe to other tracks in the room
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool CanSubscribe {
      get { if ((_hasBits0 & 1) != 0) { return canSubscribe_; } else { return CanSubscribeDefaultValue; } }
      set {
        _hasBits0 |= 1;
        canSubscribe_ = value;
      }
    }
    /// <summary>Gets whether the "can_subscribe" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCanSubscribe {
      get { return (_hasBits0 & 1) != 0; }
    }
    /// <summary>Clears the value of the "can_subscribe" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCanSubscribe() {
      _hasBits0 &= ~1;
    }

    /// <summary>Field number for the "can_publish" field.</summary>
    public const int CanPublishFieldNumber = 2;
    private readonly static bool CanPublishDefaultValue = false;

    private bool canPublish_;
    /// <summary>
    /// allow participant to publish new tracks to room
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool CanPublish {
      get { if ((_hasBits0 & 2) != 0) { return canPublish_; } else { return CanPublishDefaultValue; } }
      set {
        _hasBits0 |= 2;
        canPublish_ = value;
      }
    }
    /// <summary>Gets whether the "can_publish" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCanPublish {
      get { return (_hasBits0 & 2) != 0; }
    }
    /// <summary>Clears the value of the "can_publish" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCanPublish() {
      _hasBits0 &= ~2;
    }

    /// <summary>Field number for the "can_publish_data" field.</summary>
    public const int CanPublishDataFieldNumber = 3;
    private readonly static bool CanPublishDataDefaultValue = false;

    private bool canPublishData_;
    /// <summary>
    /// allow participant to publish data
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool CanPublishData {
      get { if ((_hasBits0 & 4) != 0) { return canPublishData_; } else { return CanPublishDataDefaultValue; } }
      set {
        _hasBits0 |= 4;
        canPublishData_ = value;
      }
    }
    /// <summary>Gets whether the "can_publish_data" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCanPublishData {
      get { return (_hasBits0 & 4) != 0; }
    }
    /// <summary>Clears the value of the "can_publish_data" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCanPublishData() {
      _hasBits0 &= ~4;
    }

    /// <summary>Field number for the "can_publish_sources" field.</summary>
    public const int CanPublishSourcesFieldNumber = 9;
    private static readonly pb::FieldCodec<global::LiveKit.Proto.TrackSource> _repeated_canPublishSources_codec
        = pb::FieldCodec.ForEnum(72, x => (int) x, x => (global::LiveKit.Proto.TrackSource) x);
    private readonly pbc::RepeatedField<global::LiveKit.Proto.TrackSource> canPublishSources_ = new pbc::RepeatedField<global::LiveKit.Proto.TrackSource>();
    /// <summary>
    /// sources that are allowed to be published
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::LiveKit.Proto.TrackSource> CanPublishSources {
      get { return canPublishSources_; }
    }

    /// <summary>Field number for the "hidden" field.</summary>
    public const int HiddenFieldNumber = 7;
    private readonly static bool HiddenDefaultValue = false;

    private bool hidden_;
    /// <summary>
    /// indicates that it's hidden to others
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Hidden {
      get { if ((_hasBits0 & 8) != 0) { return hidden_; } else { return HiddenDefaultValue; } }
      set {
        _hasBits0 |= 8;
        hidden_ = value;
      }
    }
    /// <summary>Gets whether the "hidden" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasHidden {
      get { return (_hasBits0 & 8) != 0; }
    }
    /// <summary>Clears the value of the "hidden" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearHidden() {
      _hasBits0 &= ~8;
    }

    /// <summary>Field number for the "can_update_metadata" field.</summary>
    public const int CanUpdateMetadataFieldNumber = 10;
    private readonly static bool CanUpdateMetadataDefaultValue = false;

    private bool canUpdateMetadata_;
    /// <summary>
    /// indicates that participant can update own metadata and attributes
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool CanUpdateMetadata {
      get { if ((_hasBits0 & 16) != 0) { return canUpdateMetadata_; } else { return CanUpdateMetadataDefaultValue; } }
      set {
        _hasBits0 |= 16;
        canUpdateMetadata_ = value;
      }
    }
    /// <summary>Gets whether the "can_update_metadata" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCanUpdateMetadata {
      get { return (_hasBits0 & 16) != 0; }
    }
    /// <summary>Clears the value of the "can_update_metadata" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCanUpdateMetadata() {
      _hasBits0 &= ~16;
    }

    /// <summary>Field number for the "can_subscribe_metrics" field.</summary>
    public const int CanSubscribeMetricsFieldNumber = 12;
    private readonly static bool CanSubscribeMetricsDefaultValue = false;

    private bool canSubscribeMetrics_;
    /// <summary>
    /// if a participant can subscribe to metrics
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool CanSubscribeMetrics {
      get { if ((_hasBits0 & 32) != 0) { return canSubscribeMetrics_; } else { return CanSubscribeMetricsDefaultValue; } }
      set {
        _hasBits0 |= 32;
        canSubscribeMetrics_ = value;
      }
    }
    /// <summary>Gets whether the "can_subscribe_metrics" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCanSubscribeMetrics {
      get { return (_hasBits0 & 32) != 0; }
    }
    /// <summary>Clears the value of the "can_subscribe_metrics" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCanSubscribeMetrics() {
      _hasBits0 &= ~32;
    }

    /// <summary>Field number for the "can_manage_agent_session" field.</summary>
    public const int CanManageAgentSessionFieldNumber = 13;
    private readonly static bool CanManageAgentSessionDefaultValue = false;

    private bool canManageAgentSession_;
    /// <summary>
    /// if a participant can manage an agent session via RemoteSession (control and access state)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool CanManageAgentSession {
      get { if ((_hasBits0 & 64) != 0) { return canManageAgentSession_; } else { return CanManageAgentSessionDefaultValue; } }
      set {
        _hasBits0 |= 64;
        canManageAgentSession_ = value;
      }
    }
    /// <summary>Gets whether the "can_manage_agent_session" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasCanManageAgentSession {
      get { return (_hasBits0 & 64) != 0; }
    }
    /// <summary>Clears the value of the "can_manage_agent_session" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearCanManageAgentSession() {
      _hasBits0 &= ~64;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ParticipantPermission);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ParticipantPermission other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CanSubscribe != other.CanSubscribe) return false;
      if (CanPublish != other.CanPublish) return false;
      if (CanPublishData != other.CanPublishData) return false;
      if(!canPublishSources_.Equals(other.canPublishSources_)) return false;
      if (Hidden != other.Hidden) return false;
      if (CanUpdateMetadata != other.CanUpdateMetadata) return false;
      if (CanSubscribeMetrics != other.CanSubscribeMetrics) return false;
      if (CanManageAgentSession != other.CanManageAgentSession) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (HasCanSubscribe) hash ^= CanSubscribe.GetHashCode();
      if (HasCanPublish) hash ^= CanPublish.GetHashCode();
      if (HasCanPublishData) hash ^= CanPublishData.GetHashCode();
      hash ^= canPublishSources_.GetHashCode();
      if (HasHidden) hash ^= Hidden.GetHashCode();
      if (HasCanUpdateMetadata) hash ^= CanUpdateMetadata.GetHashCode();
      if (HasCanSubscribeMetrics) hash ^= CanSubscribeMetrics.GetHashCode();
      if (HasCanManageAgentSession) hash ^= CanManageAgentSession.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (HasCanSubscribe) {
        output.WriteRawTag(8);
        output.WriteBool(CanSubscribe);
      }
      if (HasCanPublish) {
        output.WriteRawTag(16);
        output.WriteBool(CanPublish);
      }
      if (HasCanPublishData) {
        output.WriteRawTag(24);
        output.WriteBool(CanPublishData);
      }
      if (HasHidden) {
        output.WriteRawTag(56);
        output.WriteBool(Hidden);
      }
      canPublishSources_.WriteTo(output, _repeated_canPublishSources_codec);
      if (HasCanUpdateMetadata) {
        output.WriteRawTag(80);
        output.WriteBool(CanUpdateMetadata);
      }
      if (HasCanSubscribeMetrics) {
        output.WriteRawTag(96);
        output.WriteBool(CanSubscribeMetrics);
      }
      if (HasCanManageAgentSession) {
        output.WriteRawTag(104);
        output.WriteBool(CanManageAgentSession);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (HasCanSubscribe) {
        output.WriteRawTag(8);
        output.WriteBool(CanSubscribe);
      }
      if (HasCanPublish) {
        output.WriteRawTag(16);
        output.WriteBool(CanPublish);
      }
      if (HasCanPublishData) {
        output.WriteRawTag(24);
        output.WriteBool(CanPublishData);
      }
      if (HasHidden) {
        output.WriteRawTag(56);
        output.WriteBool(Hidden);
      }
      canPublishSources_.WriteTo(ref output, _repeated_canPublishSources_codec);
      if (HasCanUpdateMetadata) {
        output.WriteRawTag(80);
        output.WriteBool(CanUpdateMetadata);
      }
      if (HasCanSubscribeMetrics) {
        output.WriteRawTag(96);
        output.WriteBool(CanSubscribeMetrics);
      }
      if (HasCanManageAgentSession) {
        output.WriteRawTag(104);
        output.WriteBool(CanManageAgentSession);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (HasCanSubscribe) {
        size += 1 + 1;
      }
      if (HasCanPublish) {
        size += 1 + 1;
      }
      if (HasCanPublishData) {
        size += 1 + 1;
      }
      size += canPublishSources_.CalculateSize(_repeated_canPublishSources_codec);
      if (HasHidden) {
        size += 1 + 1;
      }
      if (HasCanUpdateMetadata) {
        size += 1 + 1;
      }
      if (HasCanSubscribeMetrics) {
        size += 1 + 1;
      }
      if (HasCanManageAgentSession) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ParticipantPermission other) {
      if (other == null) {
        return;
      }
      if (other.HasCanSubscribe) {
        CanSubscribe = other.CanSubscribe;
      }
      if (other.HasCanPublish) {
        CanPublish = other.CanPublish;
      }
      if (other.HasCanPublishData) {
        CanPublishData = other.CanPublishData;
      }
      canPublishSources_.Add(other.canPublishSources_);
      if (other.HasHidden) {
        Hidden = other.Hidden;
      }
      if (other.HasCanUpdateMetadata) {
        CanUpdateMetadata = other.CanUpdateMetadata;
      }
      if (other.HasCanSubscribeMetrics) {
        CanSubscribeMetrics = other.CanSubscribeMetrics;
      }
      if (other.HasCanManageAgentSession) {
        CanManageAgentSession = other.CanManageAgentSession;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            CanSubscribe = input.ReadBool();
            break;
          }
          case 16: {
            CanPublish = input.ReadBool();
            break;
          }
          case 24: {
            CanPublishData = input.ReadBool();
            break;
          }
          case 56: {
            Hidden = input.ReadBool();
            break;
          }
          case 74:
          case 72: {
            canPublishSources_.AddEntriesFrom(input, _repeated_canPublishSources_codec);
            break;
          }
          case 80: {
            CanUpdateMetadata = input.ReadBool();
            break;
          }
          case 96: {
            CanSubscribeMetrics = input.ReadBool();
            break;
          }
          case 104: {
            CanManageAgentSession = input.ReadBool();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            CanSubscribe = input.ReadBool();
            break;
          }
          case 16: {
            CanPublish = input.ReadBool();
            break;
          }
          case 24: {
            CanPublishData = input.ReadBool();
            break;
          }
          case 56: {
            Hidden = input.ReadBool();
            break;
          }
          case 74:
          case 72: {
            canPublishSources_.AddEntriesFrom(ref input, _repeated_canPublishSources_codec);
            break;
          }
          case 80: {
            CanUpdateMetadata = input.ReadBool();
            break;
          }
          case 96: {
            CanSubscribeMetrics = input.ReadBool();
            break;
          }
          case 104: {
            CanManageAgentSession = input.ReadBool();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
