#!/usr/bin/env python3
"""Post-process uniffi-bindgen-cs output so it compiles with C# 9 (Unity).

uniffi-bindgen-cs emits C# 10+ syntax, but Unity pins the compiler to C# 9.
This script rewrites the generated .cs files in place:

  * file-scoped namespace (`namespace Foo;`, C# 10) becomes a block-scoped
    namespace with the body indented by four spaces
  * `return [];` in sequence converters (collection expression, C# 12) becomes
    `return System.Array.Empty<T>();`
  * method groups stored in locals (`var readFn = FfiConverterX.INSTANCE.Read;`,
    inferred delegate type, C# 10) are removed and their calls inlined
  * when the bindings use records or `init` accessors (C# 9 syntax whose
    `System.Runtime.CompilerServices.IsExternalInit` marker type is missing
    from .NET Standard 2.1), an `IsExternalInit.cs` polyfill is written next to
    the bindings; it is removed again when no longer needed

Custom types that alias an array, nullable or tuple type (`using Foo = byte[];`,
C# 12) cannot be expressed in C# 9 and are reported as errors; change the
custom type mapping in uniffi.toml instead.

Usage:
    downgrade_uniffi_bindings.py <file.cs | directory> [...]

Directories are scanned for *.cs files (non-recursive). The script is
idempotent: files that are already downgraded are left untouched.
"""

import re
import sys
from pathlib import Path

INDENT = "    "
MARKER = "//     Post-processed for C# 9 by Scripts~/downgrade_uniffi_bindings.py"
POLYFILL_NAME = "IsExternalInit.cs"
POLYFILL = f"""// <auto-generated>
//     Written by Scripts~/downgrade_uniffi_bindings.py. Do not edit.
//     The generated UniFFI bindings use C# 9 records / init accessors, which
//     require this marker type. .NET Standard 2.1 (Unity) does not ship it.
// </auto-generated>

#if !NET5_0_OR_GREATER
namespace System.Runtime.CompilerServices
{{
{INDENT}internal static class IsExternalInit {{ }}
}}
#endif
"""

FILE_SCOPED_NAMESPACE = re.compile(r"^\s*namespace\s+([A-Za-z_][\w.]*)\s*;\s*$")
# `public override T[] Read(BigEndianStream stream) {` in SequenceTemplate.cs
ARRAY_READ_SIGNATURE = re.compile(r"^\s*public\s+override\s+(?P<element>.+?)\s*\[\]\s+Read\s*\(\s*BigEndianStream\b")
EMPTY_COLLECTION_RETURN = re.compile(r"^(?P<indent>\s*)return\s*\[\s*\]\s*;\s*$")
# `using Alias = Target;` — C# 9 only allows (qualified, possibly generic) type names as Target
TYPE_ALIAS = re.compile(r"^\s*using\s+[A-Za-z_@]\w*\s*=\s*(?P<target>[^;]+);\s*$")
VALID_ALIAS_TARGET = re.compile(r"^[A-Za-z_@][\w.]*(\s*<.*>)?\s*$")
# `var readFn = FfiConverterX.INSTANCE.Read;` in SequenceTemplate.cs / MapTemplate.cs
METHOD_GROUP_LOCAL = re.compile(
    r"^\s*var\s+(?P<name>[A-Za-z_]\w*)\s*=\s*(?P<target>[A-Za-z_][\w.]*\.(?:Read|Write|AllocationSize))\s*;\s*$"
)
STRING_LITERAL = re.compile(r'\$?@?"(?:[^"\\]|\\.)*"')
RECORD_DECLARATION = re.compile(
    r"^\s*(?:(?:public|internal|private|protected|sealed|abstract|partial|static|new)\s+)*record\s+(?:struct\s+|class\s+)?[A-Za-z_@]"
)
INIT_ACCESSOR = re.compile(r"\binit\s*[;{]")


def block_scope_namespace(lines):
    """Wrap everything after a file-scoped namespace declaration into a
    block-scoped namespace. Returns (lines, changed)."""
    matches = [i for i, line in enumerate(lines) if FILE_SCOPED_NAMESPACE.match(line)]
    if not matches:
        return lines, False
    if len(matches) > 1:
        raise ValueError(f"expected a single file-scoped namespace, found {len(matches)}")

    index = matches[0]
    name = FILE_SCOPED_NAMESPACE.match(lines[index]).group(1)

    body = []
    for line in lines[index + 1 :]:
        stripped = line.strip()
        if not stripped:
            body.append("")
        elif stripped.startswith("#"):
            # Keep preprocessor directives at column 0, as CSharpier does.
            body.append(line)
        else:
            body.append(INDENT + line)

    # Drop blank lines directly inside the braces.
    while body and not body[0]:
        body.pop(0)
    while body and not body[-1]:
        body.pop()

    return lines[:index] + [f"namespace {name}", "{"] + body + ["}"], True


def replace_empty_collection_returns(lines):
    """`return [];` -> `return System.Array.Empty<T>();`, taking T from the
    enclosing `T[] Read(BigEndianStream)` signature. Returns (lines, changed)."""
    result = []
    element = None
    changed = False
    for number, line in enumerate(lines, start=1):
        signature = ARRAY_READ_SIGNATURE.match(line)
        if signature:
            element = signature.group("element").strip()
        elif "override" in line and "(" in line:
            element = None  # a different method started

        empty_return = EMPTY_COLLECTION_RETURN.match(line)
        if empty_return:
            if element is None:
                raise ValueError(f"line {number}: `return [];` outside of a sequence Read() method")
            line = f"{empty_return.group('indent')}return System.Array.Empty<{element}>();"
            changed = True
        result.append(line)
    return result, changed


def inline_method_groups(lines):
    """Drop `var fn = Converter.INSTANCE.Method;` locals and call the method
    directly wherever `fn(...)` is used in the enclosing block. Returns
    (lines, changed)."""
    lines = list(lines)
    result = []
    changed = False
    for i, line in enumerate(lines):
        local = METHOD_GROUP_LOCAL.match(line)
        if not local:
            result.append(line)
            continue

        name, target = local.group("name"), local.group("target")
        call = re.compile(rf"\b{re.escape(name)}\s*\(")
        bare = re.compile(rf"\b{re.escape(name)}\b")
        depth = 0
        for j in range(i + 1, len(lines)):
            without_strings = STRING_LITERAL.sub('""', lines[j])
            depth += without_strings.count("{") - without_strings.count("}")
            if depth < 0:
                break  # enclosing block closed
            lines[j] = call.sub(f"{target}(", lines[j])
            if bare.search(lines[j]):
                raise ValueError(
                    f"line {j + 1}: `{name}` is used as a delegate value; cannot inline method group `{target}`"
                )
        changed = True  # declaration line is dropped
    return result, changed


def check_type_aliases(lines):
    for number, line in enumerate(lines, start=1):
        alias = TYPE_ALIAS.match(line)
        if alias and not VALID_ALIAS_TARGET.match(alias.group("target")):
            raise ValueError(
                f"line {number}: `{line.strip()}` needs C# 12 (alias any type); "
                "map this custom type to a named type in uniffi.toml"
            )


def add_marker(lines):
    """Record the post-processing in the <auto-generated> header, if present."""
    if MARKER in lines:
        return lines
    for i, line in enumerate(lines[:10]):
        if line.strip() == "// </auto-generated>":
            return lines[:i] + [MARKER] + lines[i:]
    return lines


def needs_is_external_init(lines):
    return any(RECORD_DECLARATION.match(line) or INIT_ACCESSOR.search(line) for line in lines)


def process_file(path):
    """Returns (changed, needs_polyfill)."""
    raw = path.read_bytes()
    bom = raw.startswith(b"\xef\xbb\xbf")
    text = raw[3:].decode("utf-8") if bom else raw.decode("utf-8")
    newline = "\r\n" if "\r\n" in text else "\n"
    lines = text.replace("\r\n", "\n").split("\n")
    if lines and lines[-1] == "":
        lines.pop()  # trailing newline is re-added on write

    check_type_aliases(lines)
    lines, namespace_changed = block_scope_namespace(lines)
    lines, returns_changed = replace_empty_collection_returns(lines)
    lines, method_groups_changed = inline_method_groups(lines)
    changed = namespace_changed or returns_changed or method_groups_changed

    if changed:
        lines = add_marker(lines)
        out = newline.join(lines) + newline
        path.write_bytes((b"\xef\xbb\xbf" if bom else b"") + out.encode("utf-8"))

    return changed, needs_is_external_init(lines)


def sync_polyfill(directory, needed):
    """Create or remove IsExternalInit.cs (and its Unity .meta) in `directory`."""
    polyfill = directory / POLYFILL_NAME
    if needed:
        if not polyfill.exists() or polyfill.read_text(encoding="utf-8") != POLYFILL:
            polyfill.write_text(POLYFILL, encoding="utf-8")
            print(f"  wrote      {polyfill}")
    elif polyfill.exists() and "downgrade_uniffi_bindings.py" in polyfill.read_text(encoding="utf-8"):
        polyfill.unlink()
        print(f"  removed    {polyfill}")
        meta = polyfill.with_name(POLYFILL_NAME + ".meta")
        if meta.exists():
            meta.unlink()
            print(f"  removed    {meta}")


def main(argv):
    if len(argv) < 2:
        print(__doc__.strip())
        return 2

    status = 0
    for arg in argv[1:]:
        target = Path(arg)
        if target.is_dir():
            directory = target
            files = sorted(p for p in target.glob("*.cs") if p.name != POLYFILL_NAME)
        elif target.is_file():
            directory = target.parent
            files = [target]
        else:
            print(f"error: {target} does not exist", file=sys.stderr)
            status = 1
            continue

        polyfill_needed = False
        for path in files:
            try:
                changed, needs_polyfill = process_file(path)
            except (ValueError, UnicodeDecodeError) as exc:
                print(f"error: {path}: {exc}", file=sys.stderr)
                status = 1
                continue
            polyfill_needed |= needs_polyfill
            print(f"  {'downgraded' if changed else 'unchanged '} {path}")

        sync_polyfill(directory, polyfill_needed)

    return status


if __name__ == "__main__":
    sys.exit(main(sys.argv))
